// Backend data for tours
import kedarnathImg from "../../assets/places/kedarnath.png";
import govindghatImg from "../../assets/places/Govindghat.jpg";
import rishikeshImg from "../../assets/places/rishikesh.jpg";
import nainitalImg from "../../assets/places/nainital.jpg";
import auliImg from "../../assets/places/auli.webp";
import almoraImg from "../../assets/places/almora.jpeg";
import mussoorieImg from "../../assets/places/mussoire.jpg";
import trekkingImg from "../../assets/adventurs/tracking.jpg";
import raftingImg from "../../assets/adventurs/river-rafting.webp";
import wildlifeImg from "../../assets/adventurs/wildlife.jpg";        
import yogaImg from "../../assets/adventurs/yoga.jpg";
import roadtripImg from "../../assets/adventurs/roadtrip.jpg";
import campingImg from "../../assets/adventurs/camping.jpeg";
import skydivingImg from "../../assets/adventurs/sky-diving.jpeg";
import banjijumpingImg from "../../assets/adventurs/bungee-jumping.jpg";

// Uttarakhand Trekking Tracks images
import bedniBugyalImg from "../../assets/tracks/bedni bugyal.jpeg";
import chandrashilaImg from "../../assets/tracks/chandrshilla.jpg";
import kedartalImg from "../../assets/tracks/kedartal-trek-trekup-india-1-1024x682.webp";
import kuariPassImg from "../../assets/tracks/khurri passs.jpeg";
import nandaDeviImg from "../../assets/tracks/nanda devi.webp";

const toursData = [
  {
    id: 1,
    title: "7-Day Char Dham Yatra (Deluxe)",
    destination: "Uttarakhand: Kedarnath, Badrinath",
    duration: 7,
    style: "Pilgrimage",
    rating: 4.8,
    reviews: 210,
    price: 34990,
    originalPrice: 40000,
    onSale: true,
    icon: "ph-mountain",
    category: "Pilgrimage",
    image: kedarnathImg, // image added
  },
  {
    id: 2,
    title: "5-Day Valley of Flowers Trek",
    destination: "Uttarakhand: Govindghat, Hemkund",
    duration: 5,
    style: "Trekking",
    rating: 5.0,
    reviews: 188,
    price: 15500,
    originalPrice: null,
    onSale: false,
    icon: "ph-flower-lotus",
    category: "Trekking",
    image: govindghatImg,
  },
  {
    id: 3,
    title: "3-Day Rishikesh Adventure Camp",
    destination: "Uttarakhand: Rishikesh, Shivpuri",
    duration: 3,
    style: "Adventure Sports",
    rating: 4.7,
    reviews: 310,
    price: 9990,
    originalPrice: null,
    onSale: false,
    icon: "ph-boat",
    category: "Adventure",
    image: rishikeshImg,
  },
  {
    id: 4,
    title: "4-Day Nainital & Kumaon Family Tour",
    destination: "Uttarakhand: Nainital, Bhimtal",
    duration: 4,
    style: "Family",
    rating: 4.6,
    reviews: 95,
    price: 18000,
    originalPrice: 20000,
    onSale: true,
    icon: "ph-users-three",
    category: "Family",
    image: nainitalImg,
  },
  {
    id: 5,
    title: "6-Day Auli Snow & Trekking Expedition",
    destination: "Uttarakhand: Joshimath, Auli",
    duration: 6,
    style: "Winter Sports",
    rating: 4.9,
    reviews: 150,
    price: 28000,
    originalPrice: null,
    onSale: false,
    icon: "ph-ski",
    category: "Trekking",
    image: auliImg,
  },
  {
    id: 6,
    title: "Almora Kumaon Hills Adventure",
    destination: "Uttarakhand: Almora, Kumaon",
    duration: 4,
    style: "Sightseeing",
    rating: 4.4,
    reviews: 75,
    price: 19900,
    originalPrice: 21000,
    onSale: false,
    icon: "ph-tree-evergreen",
    category: "Kumaon",
    image: almoraImg,
  },
  {
    id: 7,
    title: "Nainital Lake District Trip",
    destination: "Uttarakhand: Nainital, Bhimtal",
    duration: 3,
    style: "Family",
    rating: 4.6,
    reviews: 120,
    price: 14900,
    originalPrice: null,
    onSale: true,
    icon: "ph-drop",
    category: "Kumaon",
    image: nainitalImg,
  },
  {
    id: 8,
    title: "Ganga Rishikesh White Water Rafting",
    destination: "Uttarakhand: Rishikesh, Rafting",
    duration: 2,
    style: "Adventure Sports",
    rating: 4.9,
    reviews: 450,
    price: 29900,
    originalPrice: null,
    onSale: false,
    icon: "ph-tent",
    category: "Adventure",
    image: rishikeshImg,
  },
  {
    id: 9,
    title: "Mussoorie Queen of Hills Scenic Tour",
    destination: "Uttarakhand: Mussoorie, Dehradun",
    duration: 5,
    style: "Family",
    rating: 4.5,
    reviews: 105,
    price: 24900,
    originalPrice: 26000,
    onSale: false,
    icon: "ph-cable-car",
    category: "Family",
    image: mussoorieImg,
  },
  {
    id: 101,
    title: "4-Day Chopta Chandrashila Summit Trek",
    destination: "Uttarakhand: Chopta, Tungnath, Chandrashila",
    duration: 4,
    style: "Trekking",
    rating: 4.9,
    reviews: 240,
    price: 8499,
    originalPrice: 11999,
    onSale: true,
    icon: "ph-mountain",
    category: "Trekking",
    image: chandrashilaImg,
    altitude: "13,100 ft",
    difficulty: "Moderate",
    badge: "Highest Shiva Temple",
  },
  {
    id: 102,
    title: "7-Day Kedartal High Glacial Lake Trek",
    destination: "Uttarakhand: Gangotri, Kedartal",
    duration: 7,
    style: "Trekking",
    rating: 4.9,
    reviews: 165,
    price: 16990,
    originalPrice: 21500,
    onSale: true,
    icon: "ph-drop",
    category: "Trekking",
    image: kedartalImg,
    altitude: "15,500 ft",
    difficulty: "Challenging",
    badge: "Glacial Tarn",
  },
  {
    id: 103,
    title: "5-Day Bedni Bugyal Alpine Meadow Trek",
    destination: "Uttarakhand: Lohajung, Bedni Kund",
    duration: 5,
    style: "Trekking",
    rating: 4.8,
    reviews: 198,
    price: 10490,
    originalPrice: 14000,
    onSale: true,
    icon: "ph-tree-evergreen",
    category: "Trekking",
    image: bedniBugyalImg,
    altitude: "11,540 ft",
    difficulty: "Moderate",
    badge: "Asia's Finest Meadow",
  },
  {
    id: 104,
    title: "6-Day Kuari Pass Himalayan Ridge Trek",
    destination: "Uttarakhand: Joshimath, Curzon Trail",
    duration: 6,
    style: "Trekking",
    rating: 4.9,
    reviews: 210,
    price: 11990,
    originalPrice: 15500,
    onSale: true,
    icon: "ph-compass",
    category: "Trekking",
    image: kuariPassImg,
    altitude: "12,516 ft",
    difficulty: "Easy to Moderate",
    badge: "Lord Curzon Trail",
  },
  {
    id: 105,
    title: "8-Day Nanda Devi Sanctuary Base Trek",
    destination: "Uttarakhand: Lata, Nanda Devi Biosphere",
    duration: 8,
    style: "Trekking",
    rating: 5.0,
    reviews: 130,
    price: 19990,
    originalPrice: 25000,
    onSale: true,
    icon: "ph-shield-check",
    category: "Trekking",
    image: nandaDeviImg,
    altitude: "14,200 ft",
    difficulty: "Difficult",
    badge: "Sacred Sanctuary",
  },
];

export default toursData;

// src/components/Backend/BackenData.jsx

export const ADVENTURE_STYLES = [
  {
    id: 1,
    slug: "trekking-and-hiking",
    title: "Trekking & Hiking",
    badge: "Highest Himalayan Trails",
    tagline: "Scale snow-crested summits, discover crystal glacial lakes, and walk ancient shepherd paths.",
    description:
      "Scale iconic Himalayan peaks, discover hidden high-altitude lakes, and traverse lush forests.",
    overview:
      "Uttarakhand is the legendary cradle of Indian Himalayan trekking. Spanning the towering Garhwal and Kumaon ranges, each trail weaves breathtaking wilderness with mythological folklore. Whether you are stepping onto the crisp snows of Kedarkantha Summit, walking through the floral paradise of Valley of Flowers, or traversing the mystical trails of Har Ki Dun beneath the Swargarohini peaks, you will witness dramatic mountain vistas and authentic Himalayan hospitality.",
    icon: "ph-mountains-fill",
    example: "Kedarkantha, Valley of Flowers, Har Ki Dun",
    color: "text-emerald-500",
    themeBg: "from-emerald-600 to-teal-800",
    accentBorder: "border-emerald-500",
    imageUrl: trekkingImg,
    stats: {
      difficulty: "Moderate - Hard",
      bestSeason: "Mar–Jun & Sep–Dec",
      duration: "3 – 8 Days",
      altitude: "Up to 14,100 ft",
      idealFor: "Trekkers & Groups",
    },
    highlights: [
      {
        icon: "ph-mountain-fill",
        title: "Iconic Himalayan Summits",
        desc: "Reach legendary summits like Kedarkantha (12,500 ft) and Chandrashila (13,100 ft) with 360-degree panoramas of Nanda Devi, Chaukhamba, and Trishul.",
      },
      {
        icon: "ph-flower-lotus-fill",
        title: "UNESCO World Heritage Flora",
        desc: "Wander across the Valley of Flowers carpeted with over 500 varieties of endemic alpine wildflowers blooming between July and September.",
      },
      {
        icon: "ph-tent-fill",
        title: "Pristine Alpine Camping",
        desc: "Sleep under billions of stars in insulated four-season dome tents pitched on velvet green Bugyals (high-altitude meadows).",
      },
      {
        icon: "ph-shield-check-fill",
        title: "Certified Mountain Leadership",
        desc: "Every trek is led by IMF & Nehru Institute of Mountaineering (NIM) certified trek leaders equipped with emergency oxygen and first-aid kits.",
      },
    ],
    destinations: [
      {
        name: "Kedarkantha Summit Trek",
        altitude: "12,500 ft",
        duration: "5 Days / 4 Nights",
        difficulty: "Easy - Moderate",
        tag: "Best Winter Snow Trek",
        desc: "A mesmerizing trail through pine and oak forests, frozen Juda Ka Talab lake, and an exhilarating sunrise push to the 360° summit.",
      },
      {
        name: "Valley of Flowers & Hemkund Sahib",
        altitude: "14,100 ft",
        duration: "6 Days / 5 Nights",
        difficulty: "Moderate",
        tag: "UNESCO World Heritage",
        desc: "Traverse a vibrant valley of wild lilies, blue poppies, and orchids, leading to the world's highest sacred glacier lake at Hemkund Sahib.",
      },
      {
        name: "Chopta - Tungnath - Chandrashila",
        altitude: "13,100 ft",
        duration: "4 Days / 3 Nights",
        difficulty: "Moderate",
        tag: "Highest Shiva Temple",
        desc: "Hike through the rhododendron-rich meadows of Chopta (Mini Switzerland) up to Tungnath temple and the spectacular Chandrashila peak.",
      },
      {
        name: "Har Ki Dun (Valley of Gods)",
        altitude: "11,700 ft",
        duration: "7 Days / 6 Nights",
        difficulty: "Moderate",
        tag: "Ancient Mythological Trail",
        desc: "Cradle-shaped valley nestled beneath the Swargarohini peaks, dotted with 1,000-year-old carved wooden villages of Osla and Gangad.",
      },
    ],
    included: [
      "IMF & NIM Certified Trek Leaders & Support Crew",
      "High-grade Alpine Dome Tents, Sleeping Bags & Insulated Mattresses",
      "All Vegetarian Himalayan Meals (Breakfast, Packed Lunch, Evening Snacks, Hot Dinner)",
      "Forest Entry Permits, Eco Camping Fees & Camping Charges",
      "Medical Safety Kit, Pulse Oximeter, Oxygen Cylinders & Stretcher",
      "Mule / Porter Logistics for Common Camping Equipment",
    ],
    packingList: [
      "Sturdy, waterproof trekking shoes with deep ankle support",
      "3-layer clothing: Thermal base, fleece mid-layer, and waterproof down jacket",
      "40L-60L ergonomic backpack with rain cover",
      "Quick-dry trek pants, thermal innerwear, and moisture-wicking tees",
      "UV protection sunglasses (Category 3 or 4) and Sunscreen SPF 50+",
      "Trekking poles, LED headlamp with extra batteries, and personal water bladder",
    ],
    faqs: [
      {
        q: "Do I need prior trekking experience?",
        a: "No, popular treks like Kedarkantha, Chopta-Chandrashila, and Valley of Flowers are very beginner-friendly for anyone with basic cardiovascular fitness and enthusiasm.",
      },
      {
        q: "What is the policy for Acute Mountain Sickness (AMS)?",
        a: "Our itineraries are meticulously designed with acclimatization days. Trek leaders monitor blood oxygen levels twice daily and carry medical oxygen cylinders and first aid.",
      },
      {
        q: "Are toilet facilities available during the trek?",
        a: "Yes, dry pit toilet tents with hygienic toilet seats and sawdust are set up at every campsite in full accordance with Leave No Trace environmental guidelines.",
      },
      {
        q: "What kind of food is served on high altitude treks?",
        a: "Fresh, warm, high-carbohydrate vegetarian meals prepared by mountain cooks, including dal, rice, rotis, sabzi, eggs (where preferred), warm soups, and hot tea.",
      },
    ],
    relatedTourIds: [2, 5],
  },
  {
    id: 2,
    slug: "aquatic-adventures",
    title: "Aquatic Adventures",
    badge: "Ultimate River Thrills",
    tagline: "Conquer roaring Grade III-IV+ Ganges rapids, leap from cliffs, and feel the surging Himalayan rush.",
    description:
      "Conquer the mighty Ganges with white-water rafting, or try kayaking, canyoning near Rishikesh.",
    overview:
      "Fed by the melting glaciers of Bhagirathi and Alaknanda, Uttarakhand's roaring rivers carve some of the world's most thrilling white-water courses. Rishikesh stands proudly as the white-water capital of India. Navigate legendary rapids such as 'Roller Coaster', 'Golf Course', 'Three Blind Mice', and 'The Wall' with International Rafting Federation (IRF) certified captains, or leap from 30-foot granite cliffs into crystal-clear turquoise pools.",
    icon: "ph-waves-fill",
    example: "Rishikesh Rafting, Kayaking in Shivpuri",
    color: "text-blue-500",
    themeBg: "from-blue-600 to-cyan-800",
    accentBorder: "border-blue-500",
    imageUrl: raftingImg,
    stats: {
      difficulty: "Beginner to Thrill Seeker",
      bestSeason: "September – June",
      duration: "1 – 4 Days",
      altitude: "1,200 – 2,500 ft",
      idealFor: "Adrenaline Junkies, Friends & Adventure Lovers",
    },
    highlights: [
      {
        icon: "ph-waves-fill",
        title: "Grade III to IV+ White Water",
        desc: "Paddle through furious emerald waves and technical hydro-drops with seasoned river captains.",
      },
      {
        icon: "ph-arrow-up-right-bold",
        title: "Cliff Jumping & Body Surfing",
        desc: "Experience zero-gravity cliff jumps from 25-30 ft natural rock ledges and float safely in deep river channels.",
      },
      {
        icon: "ph-tent-fill",
        title: "Riverside Sand Beach Camping",
        desc: "Stay in luxury riverside safari camps on Shivpuri's silvery beaches with beach volleyball and evening bonfires.",
      },
      {
        icon: "ph-drop-fill",
        title: "Waterfall Rappelling & Canyoning",
        desc: "Rappel down roaring natural cascades in the secluded Neer Garh and Patna gorges.",
      },
    ],
    destinations: [
      {
        name: "Marine Drive to Rishikesh (26 km)",
        altitude: "1,400 ft",
        duration: "Full Day / 4-5 Hours Rafting",
        difficulty: "Grade III - IV+",
        tag: "Ultimate Adrenaline Rush",
        desc: "Runs through famous rapids: Three Blind Mice, Cross Fire, Roller Coaster, and Golf Course with cliff jumping.",
      },
      {
        name: "Shivpuri to NIM Beach (16 km)",
        altitude: "1,350 ft",
        duration: "Half Day / 3 Hours",
        difficulty: "Grade II - III+",
        tag: "The Classic Favorite",
        desc: "The most popular stretch in India, ideal for beginners and friends looking for thrilling wave-trains.",
      },
      {
        name: "Tons River Expedition (Mori)",
        altitude: "3,800 ft",
        duration: "4 Days Expedition",
        difficulty: "Grade IV - V",
        tag: "Hardcore Expedition",
        desc: "Known as India's most technical and ferocious river, rushing through deep Garhwal ravines.",
      },
      {
        name: "Brahmapuri to Rishikesh (9 km)",
        altitude: "1,250 ft",
        duration: "2 Hours",
        difficulty: "Grade I - II",
        tag: "Family & Beginners",
        desc: "Gentle rolling rapids with calm stretches for floating, swimming, and scenic mountain views.",
      },
    ],
    included: [
      "IRF-Certified River Guides, Safety Kayakers & Rescue Teams",
      "High-grade Inflatable Rafts, Paddles, Life Jackets & Helmets (CE/ISO Approved)",
      "Cliff Jumping and Body Surfing gear & guidance",
      "All Transport from Rishikesh Base to Launch Points",
      "Riverside Camp Accommodation with Attached Bath & Buffet Meals (for camp packages)",
      "First Aid Equipment & Safety Briefing",
    ],
    packingList: [
      "Quick-drying synthetic swimwear / nylon shorts and T-shirts",
      "River footwear: Strapped sandals or water shoes with non-slip grip",
      "Waterproof dry bag or waterproof phone pouch",
      "Extra change of warm clothes for post-rafting change",
      "High SPF waterproof sunscreen and sunglasses with floating strap",
      "Quick-dry microfiber towel",
    ],
    faqs: [
      {
        q: "Is swimming ability mandatory for white water rafting?",
        a: "No! High-flotation CE-certified life jackets are provided that keep you afloat even if you cannot swim, and every raft is manned by licensed guides.",
      },
      {
        q: "What is the age limit for rafting?",
        a: "For standard stretches (16km Shivpuri), the minimum age is 14 years and maximum recommended age is 65 years in good physical health.",
      },
      {
        q: "When is the rafting season closed?",
        a: "Rafting in Uttarakhand is closed during the monsoon months (July 1 to mid-September) for safety due to high water discharge.",
      },
      {
        q: "Are cameras allowed on the raft?",
        a: "Action cameras (GoPro) with helmet mounts are allowed. Most guides also carry waterproof dry bags for small personal items.",
      },
    ],
    relatedTourIds: [8, 3],
  },
  {
    id: 3,
    slug: "wildlife-safari",
    title: "Wildlife Safari",
    badge: "Untamed Foothills",
    tagline: "Track royal Bengal tigers, wild elephant herds, and over 600 exotic bird species across dense sal jungles.",
    description:
      "Explore the biodiversity of the Himalayan foothills. Spot tigers, elephants, and leopards in national parks.",
    overview:
      "Cradled where the mighty Himalayas meet the Terai lowlands, Uttarakhand preserves some of Asia's most pristine wilderness. Jim Corbett National Park—India's first national park established in 1936—holds the world's highest tiger density. Venture in open 4x4 gypsies through dense sal canopies and expansive grasslands (Chours) to watch wild elephant herds bathe in the Ramganga River, spot leopards, sloth bears, marsh crocodiles, and hundreds of vibrant bird species.",
    icon: "ph-paw-print-fill",
    example: "Jim Corbett National Park, Rajaji Reserve",
    color: "text-amber-500",
    themeBg: "from-amber-700 to-emerald-900",
    accentBorder: "border-amber-500",
    imageUrl: wildlifeImg,
    stats: {
      difficulty: "Easy / Family Friendly",
      bestSeason: "November – June (Dhikala zone opens Nov 15)",
      duration: "2 – 5 Days",
      altitude: "1,000 – 4,000 ft",
      idealFor: "Wildlife Photographers, Families, Birders",
    },
    highlights: [
      {
        icon: "ph-paw-print-fill",
        title: "Royal Bengal Tiger Tracking",
        desc: "Explore core tiger zones (Dhikala, Bijrani, Jhirna) with veteran naturalists reading pugmarks and alarm calls.",
      },
      {
        icon: "ph-binoculars-fill",
        title: "600+ Avian Species Haven",
        desc: "Spot Great Pied Hornbills, Pallas's Fish Eagles, Collared Falconets, and Crested Kingfishers.",
      },
      {
        icon: "ph-jeep-fill",
        title: "Exclusive 4x4 Gypsy Safaris",
        desc: "Open top morning and evening safaris deep through grasslands, riverbeds, and century-old sal woodlands.",
      },
      {
        icon: "ph-tree-evergreen-fill",
        title: "Historic British-Era Forest Lodges",
        desc: "Experience staying inside the core zone in heritage forest rest houses surrounded by the nocturnal wild.",
      },
    ],
    destinations: [
      {
        name: "Jim Corbett National Park (Dhikala & Bijrani)",
        altitude: "1,200 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Highest Tiger Density",
        desc: "The crown jewel of Corbett boasting sweeping Ramganga reservoir views, vast elephant herds, and tiger sightings.",
      },
      {
        name: "Rajaji Tiger Reserve (Chilla & Motichur)",
        altitude: "1,100 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Easy",
        tag: "Elephant Corridors",
        desc: "Nestled along the Shivalik range, renowned for grand wild Asian tuskers, leopards, and 315 bird species.",
      },
      {
        name: "Binsar Wildlife Sanctuary",
        altitude: "7,900 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy Walking",
        tag: "High Altitude Birding",
        desc: "Dense oak and rhododendron forest with zero vehicular noise and 300km Himalayan snow-peak panoramas.",
      },
      {
        name: "Asan Wetland Conservation Reserve",
        altitude: "1,300 ft",
        duration: "Day Excursion",
        difficulty: "Easy",
        tag: "Ramsar Wetland Site",
        desc: "Vital winter stopover for thousands of migratory waterfowl traveling across the trans-Himalayan flyway.",
      },
    ],
    included: [
      "Authorized Open 4x4 Gypsy Vehicle & Forest Driver",
      "Mandatory Government Forest Naturalist / Guide",
      "National Park Entry Permits, Vehicle Road Taxes & Camera Fees",
      "Resort / Jungle Lodge Stays with All Meals",
      "Pick-up and Drop from Ramnagar / Haridwar Railway Station",
    ],
    packingList: [
      "Earthy clothing (khaki, olive, brown, dark green; avoid bright red/yellow)",
      "Warm fleece jacket, gloves, and muffler for chilly morning open-gypsy drives",
      "High-magnification binoculars (8x42 or 10x42)",
      "DSLR / Mirrorless camera with 200mm+ telephoto lens",
      "Dust mask or scarf to protect against dry forest dust",
      "Government photo ID (Passport / Aadhaar) matching safari permit",
    ],
    faqs: [
      {
        q: "How early should I book Corbett safari permits?",
        a: "Safari permits for core zones like Dhikala and Bijrani open 45 days in advance for Indian citizens and 90 days for foreigners. Booking early is strongly advised.",
      },
      {
        q: "Are safaris safe for young children and elderly travelers?",
        a: "Yes! Safaris are conducted in private 4x4 gypsies under strict forest department guidelines and are suitable for all age groups.",
      },
      {
        q: "Which safari zone offers the best chance of spotting a tiger?",
        a: "Dhikala is famous for the highest visibility across open grasslands. Bijrani and Jhirna also have exceptionally high tiger and leopard encounter rates.",
      },
      {
        q: "Is walking allowed inside the national park?",
        a: "Walking is strictly prohibited inside Jim Corbett core zones. Walking safaris and nature trails are permitted only in Binsar Wildlife Sanctuary and buffer eco-tourism zones.",
      },
    ],
    relatedTourIds: [4, 6],
  },
  {
    id: 4,
    slug: "pilgrimage-and-spirituality",
    title: "Pilgrimage & Spirituality",
    badge: "Sacred Land of the Gods",
    tagline: "Journey through Devbhoomi to the sacred shrines of Char Dham, ancient Panch Kedar, and divine ashrams.",
    description:
      "Journey to the holy shrines of Char Dham, meditate in Rishikesh ashrams, and seek blessings.",
    overview:
      "Since Vedic antiquity, Uttarakhand has been revered as Devbhoomi—the Sacred Abode of the Gods. Here the holy rivers Ganga and Yamuna descend from heavenly glaciers, and sacred shrines stand enveloped by colossal snow peaks. Fulfill the lifetime dream of completing the Char Dham Yatra (Yamunotri, Gangotri, Kedarnath, and Badrinath), meditate in Himalayan caves where the sages discovered yoga, and immerse in the celestial evening Ganga Aarti at Haridwar.",
    icon: "ph-house-line-fill",
    example: "Char Dham Yatra, Haridwar Ganga Aarti",
    color: "text-orange-500",
    themeBg: "from-amber-600 to-orange-800",
    accentBorder: "border-orange-500",
    imageUrl: kedarnathImg,
    stats: {
      difficulty: "Moderate",
      bestSeason: "May – June & September – November",
      duration: "4 – 12 Days",
      altitude: "Up to 11,755 ft (3,584m)",
      idealFor: "Devotees, Families, Spiritual Seekers",
    },
    highlights: [
      {
        icon: "ph-house-line-fill",
        title: "Sacred Char Dham Yatra",
        desc: "Complete the soul-cleansing Himalayan pilgrimage to Yamunotri, Gangotri, Kedarnath, and Badrinath with VIP darshan assistance.",
      },
      {
        icon: "ph-fire-fill",
        title: "Twilight Ganga Aarti",
        desc: "Witness thousands of glowing brass lamps, fragrant incense, and Vedic hymns at Har Ki Pauri and Parmarth Niketan.",
      },
      {
        icon: "ph-path-fill",
        title: "Panch Prayag Holy Confluences",
        desc: "Visit the five sacred river confluences (Devprayag, Rudraprayag, Karnaprayag, Nandaprayag, Vishnuprayag).",
      },
      {
        icon: "ph-sparkle-fill",
        title: "Heli-Yatra & Priority Darshan",
        desc: "Option for Kedarnath helicopter shuttle services from Phata / Guptkashi and pre-booked biometric passes.",
      },
    ],
    destinations: [
      {
        name: "Kedarnath Jyotirlinga (3,584m)",
        altitude: "11,755 ft",
        duration: "3-4 Days Excursion",
        difficulty: "Moderate",
        tag: "Highest of 12 Jyotirlingas",
        desc: "Nestled against the colossal Kedarnath peak, revered by millions as the eternal dwelling of Lord Shiva.",
      },
      {
        name: "Badrinath Dham (3,133m)",
        altitude: "10,279 ft",
        duration: "2-3 Days Excursion",
        difficulty: "Easy (Road Access)",
        tag: "Vaikuntha on Earth",
        desc: "The sacred black stone shrine of Lord Badri Vishal, guarded by the Nar and Narayan mountains beside the hot Tapt Kund springs.",
      },
      {
        name: "Gangotri & Yamunotri Dhams",
        altitude: "10,200 ft",
        duration: "4 Days Excursion",
        difficulty: "Moderate",
        tag: "Cradle of Sacred Rivers",
        desc: "The pristine high-altitude sources of the two holiest rivers of India flowing through dramatic granite canyons.",
      },
      {
        name: "Haridwar & Rishikesh Ghats",
        altitude: "1,050 ft",
        duration: "2-3 Days",
        difficulty: "Easy",
        tag: "Spiritual Gateways",
        desc: "Century-old temples, holy snan ghats, ashrams, and the legendary evening Ganga Aarti.",
      },
    ],
    included: [
      "AC Vehicle for all Sightseeing & Transfers across Mountain Routes",
      "Clean Handpicked Deluxe Hotel & Camp Stays with Geyser Facilities",
      "Pure Vegetarian Breakfast & Dinner (Satvik / Jain Options Available)",
      "Mandatory Biometric Registration & Yatra Pass Assistance",
      "Experienced Mountain Chauffeur & 24/7 Ground Support Team",
    ],
    packingList: [
      "Warm woolens: Thermals, heavy fleece jacket, woolen cap, and gloves",
      "Comfortable walking shoes with good grip for Kedarnath/Yamunotri treks",
      "Rainwear: Raincoat, umbrella, or waterproof poncho",
      "Personal medical kit: Altitude sickness pills, pain relief, glucose, and band-aids",
      "Power bank and cash (ATMs in high mountain sectors are often out of cash)",
      "Aadhaar Card / Government photo ID & Yatra Registration slip",
    ],
    faqs: [
      {
        q: "What is the best way to travel to Kedarnath?",
        a: "You can either trek the scenic 16 km trail from Gaurikund on foot, hire a pony/palanquin (palki), or take a 7-minute helicopter shuttle from Guptkashi, Phata, or Sersi.",
      },
      {
        q: "When do the Char Dham temple portals open and close?",
        a: "The portals open around Akshaya Tritiya (late April/early May) and close shortly after Diwali/Bhai Dooj in November for the winter period.",
      },
      {
        q: "Is medical certification required for the yatra?",
        a: "Basic health registration is mandatory. Senior citizens and those with heart conditions are advised to consult a physician and carry prescribed medications.",
      },
    ],
    relatedTourIds: [1, 2],
  },
  {
    id: 5,
    slug: "culture-and-heritage",
    title: "Culture & Heritage",
    badge: "Timeless Mountain Traditions",
    tagline: "Immerse in ancient stone-and-cedar architecture, living folklore, Kumaoni Aipan art, and local gastronomy.",
    description:
      "Immerse yourself in Kumaoni and Garhwali cultures. Visit centuries-old temples and enjoy local cuisine.",
    overview:
      "The twin mountain kingdoms of Garhwal and Kumaon hold a vibrant heritage woven over centuries. Walk cobblestone pathways through Almora's 500-year-old bazaar, admire 1,000-year-old stone temple carvings at Jageshwar nestled amidst ancient deodar forests, learn traditional red-and-white Aipan folk painting, and savor organic Pahadi culinary delicacies like Bhatt ki Churkani and Singori while residing in restored heritage village homestays.",
    icon: "ph-handshake-fill",
    example: "Almora, Kausani, Local Homestays",
    color: "text-purple-500",
    themeBg: "from-purple-700 to-indigo-900",
    accentBorder: "border-purple-500",
    imageUrl: almoraImg,
    stats: {
      difficulty: "Easy / Leisure",
      bestSeason: "All 12 Months",
      duration: "3 – 7 Days",
      altitude: "4,000 – 7,500 ft",
      idealFor: "Culture Lovers, Families, Explorers",
    },
    highlights: [
      {
        icon: "ph-house-line-fill",
        title: "Traditional Kath-Kuni Homestays",
        desc: "Stay in heritage stone-and-deodar dwellings, sharing meals with warm local mountain families.",
      },
      {
        icon: "ph-paint-brush-broad-fill",
        title: "Hands-on Aipan Art Workshops",
        desc: "Learn sacred geometric floor and wall art using red clay (Geru) and ground rice paste.",
      },
      {
        icon: "ph-bank-fill",
        title: "Ancient Stone Temple Clusters",
        desc: "Explore Jageshwar Dham's 124 monolithic stone shrines dating from the 7th to 12th centuries.",
      },
      {
        icon: "ph-bowl-food-fill",
        title: "Authentic Pahadi Culinary Feasts",
        desc: "Savor Kafuli, Chainsoo, Mandua rotis, Jhangora kheer, and sweet Bal Mithai.",
      },
    ],
    destinations: [
      {
        name: "Jageshwar Dham & Almora Heritage",
        altitude: "6,200 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Archaeological Marvel",
        desc: "Surrounded by towering deodars, Jageshwar is one of India's most mystical ancient Shiva complexes.",
      },
      {
        name: "Kausani & Baijnath Valley",
        altitude: "6,200 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Switzerland of India",
        desc: "Panoramic 300km vistas of Nanda Devi and Trishul peaks, tea gardens, and 12th-century river temples.",
      },
      {
        name: "Mana Village (First Village of India)",
        altitude: "10,500 ft",
        duration: "Day Excursion from Badrinath",
        difficulty: "Easy Walk",
        tag: "Indo-Tibetan Border Heritage",
        desc: "Ancient Bhotia tribal village famous for handmade woolens, Vyas Gufa, and the dramatic Bhim Pul stone bridge.",
      },
      {
        name: "Lansdowne & Pauri Garhwal",
        altitude: "5,600 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Colonial & Folk History",
        desc: "Pristine pine forests, heritage churches, and panoramic views of the western Garhwal range.",
      },
    ],
    included: [
      "Authentic Heritage Homestay / Boutique Hotel Stays",
      "Traditional Kumaoni & Garhwali Breakfasts and Dinners",
      "Guided Walking Tours with Local Heritage Experts",
      "Aipan Folk Art Workshop & Local Craft Interactions",
      "Private Vehicle Transport with Experienced Local Chauffeur",
    ],
    packingList: [
      "Comfortable walking shoes for village strolls and cobbled markets",
      "Warm layers (sweaters / jackets) as mountain evenings can be cool",
      "Camera for capturing intricate temple carvings and village portraits",
      "Modest clothing for visiting revered temple complexes",
      "Eco-friendly reusable water bottle and shopping bag for local handicrafts",
    ],
    faqs: [
      {
        q: "What is special about Uttarakhand's village homestays?",
        a: "They offer an authentic glimpse into mountain life. You eat organic farm-to-table food, sleep in century-old timber homes, and support sustainable local village economies.",
      },
      {
        q: "Can children and seniors participate comfortably?",
        a: "Absolutely! Culture and heritage tours involve relaxed sightseeing, scenic road journeys, and gentle walks suitable for all generations.",
      },
    ],
    relatedTourIds: [6, 7, 4],
  },
  {
    id: 6,
    slug: "wellness-and-yoga-retreats",
    title: "Wellness & Yoga Retreats",
    badge: "Mindful Himalayan Awakening",
    tagline: "Harmonize your inner self in the world capital of Yoga with authentic Ayurveda, meditation, and detox.",
    description:
      "Find peace and rejuvenation in the lap of the mountains with yoga, meditation, and detox programs.",
    overview:
      "Where the sacred river Ganga flows out of the pristine Himalayas, surrounded by tranquil wooded foothills, lies Rishikesh—the Yoga Capital of the World. Disconnect from digital overwhelm and step into an oasis of mindfulness. Greet the dawn with Ganga-side pranayama and asana practices, nourish your body with wholesome satvik Ayurvedic nutrition, and experience deeply restorative sound baths and meditation guided by Himalayan masters.",
    icon: "ph-leaf-fill",
    example: "Rishikesh Yoga Schools, Wellness Centers",
    color: "text-rose-500",
    themeBg: "from-rose-600 to-pink-900",
    accentBorder: "border-rose-500",
    imageUrl: yogaImg,
    stats: {
      difficulty: "All Levels / Restorative",
      bestSeason: "September – May",
      duration: "3 – 14 Days",
      altitude: "1,200 – 5,000 ft",
      idealFor: "Solo Seekers, Couples, Wellness Enthusiasts",
    },
    highlights: [
      {
        icon: "ph-leaf-fill",
        title: "Daily Hatha & Ashtanga Yoga",
        desc: "Morning and sunset sessions overlooking the Ganga led by certified master yogis.",
      },
      {
        icon: "ph-heart-fill",
        title: "Ayurvedic Pulse Assessment & Abhyanga",
        desc: "Personalized dosha diagnosis and therapeutic warm herbal oil massages for deep detox.",
      },
      {
        icon: "ph-bell-ringing-fill",
        title: "Tibetan Sound Healing & Meditation",
        desc: "Harmonic sound bath frequencies designed to release deep-seated mental stress and anxiety.",
      },
      {
        icon: "ph-sun-dim-fill",
        title: "Organic Satvik & Detox Cuisine",
        desc: "Wholesome, freshly prepared farm-to-table Ayurvedic vegetarian cuisine that restores vitality.",
      },
    ],
    destinations: [
      {
        name: "Rishikesh Yoga Ashrams (Tapovan & Swarg Ashram)",
        altitude: "1,200 ft",
        duration: "5 to 14 Days",
        difficulty: "Gentle",
        tag: "World Yoga Capital",
        desc: "Legendary spiritual hub on the banks of the emerald Ganges, dotted with centuries-old yoga schools.",
      },
      {
        name: "Narendra Nagar Himalayan Foothills",
        altitude: "3,300 ft",
        duration: "3 to 7 Days",
        difficulty: "Luxury Restorative",
        tag: "Luxury Wellness Retreats",
        desc: "Secluded palatial estates offering world-renowned spa therapies, hydrotherapy, and panoramic valley views.",
      },
      {
        name: "Ranikhet & Kumaon Forest Sanctuaries",
        altitude: "6,000 ft",
        duration: "4 to 7 Days",
        difficulty: "Gentle",
        tag: "Forest Bathing & Silence",
        desc: "Meditate surrounded by towering pine and deodar forests with zero traffic and pure mountain prana.",
      },
    ],
    included: [
      "Serene Ashram or Boutique Wellness Resort Accommodation",
      "Two Daily Yoga & Guided Pranayama / Meditation Sessions",
      "Complete Satvik / Organic Ayurvedic Meals & Herbal Teas",
      "Doctor Consultation & Personalized Dosha Analysis",
      "Sound Healing Session & Ganga Ghat Evening Meditation",
    ],
    packingList: [
      "Comfortable, breathable cotton or linen yoga wear (white/light colors preferred)",
      "Personal yoga mat or travel mat towel",
      "Warm shawl or light blanket for early morning outdoor meditation",
      "Journal and pen for reflective journaling and insights",
      "Slip-on shoes / sandals for easy removal at ashrams and yoga halls",
    ],
    faqs: [
      {
        q: "I am a complete beginner to yoga. Can I join?",
        a: "Yes! All retreats accommodate beginners as well as seasoned practitioners. Instructors offer modifications to ensure comfort and safety.",
      },
      {
        q: "What is a Satvik diet?",
        a: "A Satvik diet emphasizes freshly cooked, seasonal, pure vegetarian foods prepared with minimal oil and spices, promoting lightness, clarity, and vitality.",
      },
    ],
    relatedTourIds: [3, 1],
  },
  {
    id: 7,
    slug: "motorcycle-and-road-trips",
    title: "Motorcycle & Road Trips",
    badge: "Open Road Mountain Freedom",
    tagline: "Ride legendary mountain asphalt, conquer hair-raising switchbacks, and witness untamed Himalayan grandeur.",
    description:
      "Experience the thrill of riding through challenging mountain passes and scenic highways on a guided bike tour.",
    overview:
      "Few thrills compare to revving an engine along the sweeping mountain curves of Uttarakhand. Trace the thunderous rivers along the all-weather Char Dham Highway, climb steep hairpin switchbacks to misty colonial hill stations, and cross soaring passes leading toward the Tibetan border. Accompanied by a dedicated support vehicle, experienced mechanics, and premier Royal Enfield Himalayan machines, you ride with absolute confidence and unfiltered freedom.",
    icon: "ph-motorcycle-fill",
    example: "Badrinath Road Trip, Remote Routes",
    color: "text-red-500",
    themeBg: "from-red-600 to-rose-900",
    accentBorder: "border-red-500",
    imageUrl: roadtripImg,
    stats: {
      difficulty: "Challenging / Experienced Riders",
      bestSeason: "April – June & September – November",
      duration: "4 – 10 Days",
      altitude: "Up to 11,500+ ft",
      idealFor: "Bikers, Roadtrippers, Riding Clubs",
    },
    highlights: [
      {
        icon: "ph-motorcycle-fill",
        title: "All-Terrain Himalayan Fleets",
        desc: "Ride fully serviced Royal Enfield Himalayan 450s & Scram 411s outfitted with crash guards and phone mounts.",
      },
      {
        icon: "ph-wrench-fill",
        title: "Dedicated Chase Truck & Mechanic",
        desc: "Complete backup vehicle carrying your heavy luggage, spare parts, tools, and a standby motorcycle.",
      },
      {
        icon: "ph-map-pin-line-fill",
        title: "High Mountain River Gorges",
        desc: "Conquer scenic highway routes along the Bhagirathi, Alaknanda, and Mandakini river valleys.",
      },
      {
        icon: "ph-camera-fill",
        title: "Curated Scenic Photo Stops",
        desc: "Pre-planned scenic pauses at cliffside roads, suspension bridges, and high-altitude alpine tea shacks.",
      },
    ],
    destinations: [
      {
        name: "Rishikesh to Badrinath & Mana",
        altitude: "10,500 ft",
        duration: "6 Days / 5 Nights",
        difficulty: "Challenging",
        tag: "Epic Highway Odyssey",
        desc: "Carve through the dramatic gorges of Panch Prayag to reach India's last frontier village at Mana.",
      },
      {
        name: "Mussoorie - Dhanaulti - Kanatal Ridge",
        altitude: "8,500 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Moderate",
        tag: "Panoramic Ridge Run",
        desc: "Smooth winding asphalt offering uninterrupted vistas of the Doon valley and the snow-capped Great Himalayas.",
      },
      {
        name: "Kumaon Circuit (Nainital - Almora - Kausani)",
        altitude: "7,000 ft",
        duration: "5 Days / 4 Nights",
        difficulty: "Moderate",
        tag: "Colonial & Tea Valley Ride",
        desc: "Glide through fragrant pine and deodar forests, lake districts, and tea plantations.",
      },
    ],
    included: [
      "Royal Enfield Himalayan 450 / Scram 411 Motorcycle with Fuel Allowance",
      "Support Vehicle (4x4 / Bolero Camper) for Luggage & Medical Equipment",
      "Professional Road Captain & Certified Lead Motorcycle Mechanic",
      "Handpicked Mountain Resort & Deluxe Camp Accommodation",
      "All Breakfasts, Trail Dinners & Welcome Refreshments",
    ],
    packingList: [
      "DOT / ECE certified full-face riding helmet",
      "All-weather motorcycle riding jacket and pants with CE Level 2 armor",
      "Waterproof riding boots with ankle and shin protection",
      "Winter and summer riding gloves (waterproof recommended)",
      "Rain gear / Over-suit for unexpected mountain showers",
      "Valid Two-Wheeler Driving License & Photo ID",
    ],
    faqs: [
      {
        q: "Can pillion riders join the motorcycle tour?",
        a: "Yes! Pillions are welcome on our Royal Enfield Himalayan bikes, or they can travel comfortably in the accompanying AC support backup vehicle.",
      },
      {
        q: "What if a motorcycle breaks down on a remote pass?",
        a: "Our chase vehicle carries full tools, spare components, and an extra motorcycle so your ride continues without delay.",
      },
    ],
    relatedTourIds: [9, 6, 8],
  },
  {
    id: 8,
    slug: "camping-and-stargazing",
    title: "Camping & Stargazing",
    badge: "Bortle-Class Dark Skies",
    tagline: "Camp under crystal-clear Himalayan skies, gaze at the Milky Way, and wake up to golden mountain sunrises.",
    description:
      "Spend nights under the clear Himalayan skies. Enjoy organized camping and breathtaking views.",
    overview:
      "Far removed from the haze and blinding light pollution of bustling cities, Uttarakhand is home to some of the world's most breathtaking dark sky sanctuaries. Locations like Chopta, Benital, Kanatal, and Deoriatal boast Bortle-Class 2 and 3 night skies where the Milky Way spans brilliantly from horizon to horizon with the naked eye. Cozy up around an alpine bonfire, look through high-powered telescopes to observe Saturn's rings, and sleep peacefully in comfortable all-weather dome tents.",
    icon: "ph-tent-fill",
    example: "Chopta, Kanatal, Deoriatal Campsites",
    color: "text-indigo-400",
    themeBg: "from-indigo-900 to-slate-950",
    accentBorder: "border-indigo-400",
    imageUrl: campingImg,
    stats: {
      difficulty: "Easy to Moderate",
      bestSeason: "October – May (Crisp dark skies & clear Milky Way)",
      duration: "2 – 5 Days",
      altitude: "6,500 – 10,000 ft",
      idealFor: "Stargazers, Couples, Campers, Astrophotographers",
    },
    highlights: [
      {
        icon: "ph-binoculars-fill",
        title: "Deep Sky Telescope Astronomy",
        desc: "Observe lunar craters, Jupiter's Galilean moons, Saturn's rings, and distant nebulae through high-aperture telescopes.",
      },
      {
        icon: "ph-camera-fill",
        title: "Milky Way Astrophotography",
        desc: "Guided evening workshops capturing the cosmic galaxy arching over the snow-crested Chaukhamba peaks.",
      },
      {
        icon: "ph-tent-fill",
        title: "Comfortable Alpine Glamping",
        desc: "Four-season waterproof dome tents equipped with insulated sleeping bags, plush foam mattresses, and warm fleece blankets.",
      },
      {
        icon: "ph-fire-fill",
        title: "Acoustic Bonfires & Hot Meals",
        desc: "Evenings around crackling campfires with steaming local Himalayan delicacies, hot chocolate, and acoustic tunes.",
      },
    ],
    destinations: [
      {
        name: "Chopta Alpine Meadows & Tungnath Base",
        altitude: "8,800 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy - Moderate",
        tag: "Mini Switzerland of India",
        desc: "Open grassy bugyals surrounded by deodars with unobstructed vistas of the massive Chaukhamba massif.",
      },
      {
        name: "Benital Dark Sky Astro Village",
        altitude: "8,500 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Easy",
        tag: "India's First Astro Village",
        desc: "State-recognized astronomy hub equipped with permanent telescope domes, stellar night views, and clean mountain air.",
      },
      {
        name: "Deoriatal High-Altitude Lake Camping",
        altitude: "7,800 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Moderate (3km Trek)",
        tag: "Mirrored Chaukhamba Reflection",
        desc: "Crystal mountain lake mirroring the snowy Himalayan peaks during the day and billions of stars at night.",
      },
      {
        name: "Kanatal & Dhanaulti Pine Forests",
        altitude: "7,500 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Easy",
        tag: "Serene Weekend Escape",
        desc: "Dense pine and cedar clearings ideal for relaxation, hammocks, zip-lining, and tranquil stargazing.",
      },
    ],
    included: [
      "Deluxe All-Weather Alpine Dome Tents with Insulated Bedding",
      "Astronomical Telescope Sessions & Sky Guide Orientation",
      "Freshly Cooked Hot Camp Meals (Evening Snacks, Dinner, Breakfast)",
      "Evening Campfire with Music & Refreshments (subject to weather/forest norms)",
      "Clean Eco-Friendly Campsite Facilities & Common Washrooms",
    ],
    packingList: [
      "Thermal base layer, warm sweater, and down jacket (nights are very cold in high altitude)",
      "Woolen cap (beanie), warm socks, and gloves",
      "Red light headlamp or flashlight (red light preserves night vision for astronomy)",
      "Camera with manual exposure mode & sturdy tripod for astrophotography",
      "Thermos flask for hot water/tea through the night",
    ],
    faqs: [
      {
        q: "How cold does it get at night while camping?",
        a: "Temperatures in Chopta and high meadows can drop between 0°C to 8°C in winter and 8°C to 15°C in summer. High-grade thermal sleeping bags ensure cozy comfort.",
      },
      {
        q: "What is the best moon phase for stargazing?",
        a: "The week around the New Moon (Amavasya) is ideal, when the sky is darkest and the Milky Way core is vividly visible.",
      },
      {
        q: "Are the campsites safe for solo female travelers and families?",
        a: "Yes! All our campsites are secured with 24/7 staff, well-lit perimeter pathways, and family-friendly staff.",
      },
    ],
    relatedTourIds: [3, 5, 2],
  },
];

// --- UTTARAKHAND ICONIC DESTINATIONS DATA ---
export const UTTARAKHAND_DESTINATIONS = [
  {
    id: "rishikesh",
    name: "Rishikesh",
    region: "Garhwal Foothills",
    title: "Yoga Capital & Ganges Rapids",
    properties: "340+ properties & river camps",
    distance: "25 km from Dehradun Airport",
    badge: "Most Popular",
    vibes: ["Spiritual & Sacred", "White Water & Adventure", "Camping & Stargazing"],
    image: rishikeshImg,
    rating: 4.8,
    searchQuery: "Rishikesh",
    highlights: ["Triveni Ghat Ganga Aarti", "Grade III/IV Rapids", "Beatles Ashram", "Cliff Jumping"],
  },
  {
    id: "nainital",
    name: "Nainital",
    region: "Kumaon Hills",
    title: "Lake District of Devbhoomi",
    properties: "215+ lakeside hotels & stays",
    distance: "285 km from Delhi",
    badge: "Scenic Lakes",
    vibes: ["Lakes & Hill Stations", "Camping & Stargazing"],
    image: nainitalImg,
    rating: 4.7,
    searchQuery: "Nainital",
    highlights: ["Naini Lake Yachting", "Snow View Ropeway", "Mall Road Promenade", "Bhimtal & Naukuchiatal"],
  },
  {
    id: "kedarnath",
    name: "Kedarnath",
    region: "Rudraprayag Valley",
    title: "Sacred Jyotirlinga & High Peaks",
    properties: "145+ pilgrim lodges & camps",
    distance: "Mandakini Valley (3,584m)",
    badge: "Holy Pilgrimage",
    vibes: ["Spiritual & Sacred", "High-Altitude Treks"],
    image: kedarnathImg,
    rating: 4.9,
    searchQuery: "Kedarnath",
    highlights: ["12th Jyotirlinga Shrine", "Mandakini River Source", "Bhairavnath Peak", "Chorabari Glacier"],
  },
  {
    id: "mussoorie",
    name: "Mussoorie",
    region: "Garhwal Shivalik",
    title: "Queen of the Hills",
    properties: "190+ colonial & valley stays",
    distance: "34 km from Dehradun",
    badge: "Romantic Getaway",
    vibes: ["Lakes & Hill Stations"],
    image: mussoorieImg,
    rating: 4.6,
    searchQuery: "Mussoorie",
    highlights: ["Kempty Cascading Falls", "Gun Hill Viewpoint", "Camel's Back Trail", "George Everest Peak"],
  },
  {
    id: "auli",
    name: "Auli",
    region: "Chamoli District",
    title: "Skiing Capital & Snow Slopes",
    properties: "98+ ski resorts & chalets",
    distance: "14 km from Joshimath",
    badge: "Winter Snow",
    vibes: ["Snow & Winter Slopes", "High-Altitude Treks"],
    image: auliImg,
    rating: 4.9,
    searchQuery: "Auli",
    highlights: ["Asia's Longest Cable Car", "Nanda Devi 360° Panoramas", "Gorson Bugyal Snow Trail", "Artificial Lake"],
  },
  {
    id: "almora",
    name: "Almora",
    region: "Kumaon Cultural Hub",
    title: "Cultural Heart & Pine Ridges",
    properties: "82+ heritage mountain stays",
    distance: "360 km from Delhi",
    badge: "Heritage Haven",
    vibes: ["Lakes & Hill Stations", "Camping & Stargazing"],
    image: almoraImg,
    rating: 4.6,
    searchQuery: "Almora",
    highlights: ["Bright End Corner Sunsets", "Kasar Devi Magnetic Ridge", "Chitai Golu Devta", "Jageshwar Dham Temples"],
  },
  {
    id: "govindghat",
    name: "Valley of Flowers",
    region: "Chamoli Biosphere",
    title: "UNESCO Floral Paradise & Hemkund",
    properties: "64+ eco camps & lodges",
    distance: "Gateway at Govindghat",
    badge: "UNESCO Heritage",
    vibes: ["High-Altitude Treks", "Lakes & Hill Stations"],
    image: govindghatImg,
    rating: 5.0,
    searchQuery: "Govindghat",
    highlights: ["500+ Alpine Wildflower Species", "Hemkund High Glacier Lake", "Pushpawati River", "Rare Blue Poppy"],
  },
  {
    id: "chopta",
    name: "Chopta",
    region: "Kedarnath Wildlife Sanctuary",
    title: "Mini Switzerland & Tungnath",
    properties: "76+ alpine dome camps",
    distance: "210 km from Rishikesh",
    badge: "Alpine Meadows",
    vibes: ["Camping & Stargazing", "High-Altitude Treks", "Snow & Winter Slopes"],
    image: chandrashilaImg,
    rating: 4.9,
    searchQuery: "Chopta",
    highlights: ["Highest Shiva Shrine (Tungnath)", "Chandrashila 360° Summit", "Deoriatal Reflection Lake", "Dark Sky Stargazing"],
  },
];

// --- UTTARAKHAND TREKKING TRACKS & EXPEDITIONS DATA ---
export const UTTARAKHAND_TRACKS = [
  {
    id: 101,
    title: "Chopta Chandrashila Summit Track",
    subtitle: "Scale the highest Shiva temple at Tungnath and conquer the 360° Chandrashila summit.",
    slug: "chopta-chandrashila-summit-track",
    region: "Garhwal Himalayas, Rudraprayag",
    startPoint: "Sari / Chopta Base",
    endPoint: "Chopta",
    durationDays: 4,
    durationNights: 3,
    altitudeFt: "13,100 ft",
    altitudeM: "3,990 m",
    difficulty: "Moderate",
    gradeColor: "emerald",
    distanceKm: "30 km",
    bestSeason: "Oct – May (Winter Snow Trek & Spring Rhododendrons)",
    price: 8499,
    originalPrice: 11999,
    rating: 4.9,
    reviews: 240,
    image: chandrashilaImg,
    category: "Summit Climbs",
    badge: "Most Popular Summit",
    vibe: "Summit Climbs",
    tags: ["Highest Shiva Temple", "360° Chaukhamba Panorama", "Mini Switzerland", "Winter Snow Trek"],
    overview:
      "Chopta to Chandrashila is one of Uttarakhand's most breathtaking summit tracks. Starting from the lush alpine hamlet of Chopta (affectionately known as the 'Mini Switzerland of India'), the trail ascends through dense oak, pine, and scarlet rhododendron woodlands to Tungnath temple (the world's highest Shiva temple at 12,070 ft), and concludes with an exhilarating sunrise scramble to the Chandrashila summit (13,100 ft). The 360-degree panoramic vista from the summit encompasses Nanda Devi, Trishul, Chaukhamba, Kedar Dome, and Bandarpoonch.",
    itinerary: [
      {
        day: 1,
        title: "Rishikesh to Sari Village & Deoriatal Hike",
        desc: "Scenic 7-hour mountain drive through Devprayag and Rudraprayag to Sari village. A gentle 2.5 km uphill trek leads to the emerald Deoriatal lake, mirroring the towering Chaukhamba peaks. Night in lakeside dome tents.",
      },
      {
        day: 2,
        title: "Deoriatal to Chopta Alpine Meadows via Rohini Bugyal",
        desc: "A mesmerizing 14 km ridge trail navigating through thick rhododendron forests, sparkling mountain streams, and the golden grass meadows of Rohini Bugyal. Settle into the Chopta basecamp.",
      },
      {
        day: 3,
        title: "Summit Day: Chopta to Tungnath & Chandrashila (13,100 ft)",
        desc: "Early 4:00 AM alpine start. Ascend stone-paved switchbacks up to the 1,000-year-old Tungnath Temple (12,070 ft). Push up the craggy trail to Chandrashila summit for an unforgettable golden sunrise across the Garhwal range. Descend to Chopta.",
      },
      {
        day: 4,
        title: "Chopta to Rishikesh / Dehradun Departure",
        desc: "Post-breakfast drive down the Mandakini and Alaknanda river gorges back to Rishikesh, carrying unforgettable memories of the summit.",
      },
    ],
    inclusions: [
      "NIM & IMF Certified Mountain Trek Leader & Local Trail Guides",
      "High-grade all-weather 4-season dome tents, insulated mattresses & -10°C sleeping bags",
      "Nutritious high-altitude vegetarian meals (Breakfast, Packed Lunch, Hot Dinner, Herbal Tea)",
      "Safety gear: Portable Medical Oxygen Cylinder, Pulse Oximeter & Stretcher Kit",
      "Mandatory Forest Department entry permits and eco-camping fees",
    ],
    packingList: [
      "Sturdy waterproof trekking shoes with deep lug grip",
      "3-layer clothing system: Thermal base, fleece mid-layer, windproof down jacket",
      "UV-protection polarized sunglasses (essential for snow glare)",
      "LED headlamp / flashlight with spare batteries",
      "2-liter insulated thermos hydration bottle",
      "Quick-dry trekking pants and woolen gloves with waterproof outer layer",
    ],
  },
  {
    id: 102,
    title: "Kedartal High Glacial Lake Track",
    subtitle: "Journey to Shiva's emerald glacial tarn directly beneath the colossal face of Mt. Thalaysagar.",
    slug: "kedartal-glacial-lake-track",
    region: "Gangotri National Park, Uttarkashi",
    startPoint: "Gangotri Shrine (3,048 m)",
    endPoint: "Gangotri",
    durationDays: 7,
    durationNights: 6,
    altitudeFt: "15,500 ft",
    altitudeM: "4,750 m",
    difficulty: "Difficult / Strenuous",
    gradeColor: "rose",
    distanceKm: "36 km",
    bestSeason: "May – June & Sept – Oct (Crystal Glacial Tarn)",
    price: 16990,
    originalPrice: 21500,
    rating: 4.9,
    reviews: 165,
    image: kedartalImg,
    category: "Glacial Alpine Tarns",
    badge: "15,500 ft High Tarn",
    vibe: "Glacial Alpine Tarns",
    tags: ["Mt. Thalaysagar Face", "Glacial Moraines", "Spider Wall Traverse", "Gangotri Wilderness"],
    overview:
      "Kedartal (also reverently known as Shiva's Lake) is one of the most dramatic and challenging high-altitude glacial tracks in the Indian Himalayas. Nestled deep inside Gangotri National Park at a staggering 15,500 ft, this emerald tarn rests right at the foot of the sheer 6,904-meter rock and ice walls of Mt. Thalaysagar, Mt. Bhrigupanth (6,772m), and the Manda peaks. Navigating steep birch forests, narrow screes, the famous Spider Wall, and rugged moraines, this is a true mountaineer's trail that rewards trekkers with profound solitude.",
    itinerary: [
      {
        day: 1,
        title: "Dehradun / Rishikesh to Gangotri Pilgrimage Town (10,000 ft)",
        desc: "A breathtaking 8-hour drive up the Bhagirathi river gorge via Uttarkashi and Harsil valley. Evening Ganga aarti at the sacred Gangotri temple and acclimatization stroll.",
      },
      {
        day: 2,
        title: "Gangotri Acclimatization & Trek to Bhoj Kharak (12,400 ft)",
        desc: "Leave the pilgrim town behind into the narrow Kedar Ganga gorge. Navigate through golden bhojpatra (Himalayan birch) forests and cross the thrilling Spider Wall rocky traverse to reach Bhoj Kharak.",
      },
      {
        day: 3,
        title: "Bhoj Kharak to Kedar Kharak High Meadow (14,000 ft)",
        desc: "Trek beyond the tree-line into barren alpine terrain. Walk across meadows carpeted with blue gentians with frequent sightings of Bharal (Himalayan blue sheep). Arrive at Kedar Kharak.",
      },
      {
        day: 4,
        title: "Kedar Kharak to Kedartal Glacial Tarn & Basecamp (15,500 ft)",
        desc: "Cross boulder-strewn glacial moraines and navigate the steep scree of the Kedar Glacier. Suddenly the mesmerizing emerald green Kedartal unfolds with Mt. Thalaysagar rising straight out of the water.",
      },
      {
        day: 5,
        title: "Exploration around Kedartal & Thalaysagar Ridge",
        desc: "Full day to soak in the monumental amphitheater of Thalaysagar, Bhrigupanth, and Jogin peaks. Astrophotography under Bortle-Class 1 night skies.",
      },
      {
        day: 6,
        title: "Kedartal to Gangotri via Bhoj Kharak Descent",
        desc: "Retrace the trail down the Kedar gorge, descending with care across the moraines and boulder fields back to Gangotri town.",
      },
      {
        day: 7,
        title: "Gangotri to Dehradun Departure",
        desc: "Morning departure drive along the Bhagirathi river, concluding this memorable high-altitude expedition.",
      },
    ],
    inclusions: [
      "Experienced Mountaineering Expedition Leader (NIM / HMI certified)",
      "Gangotri National Park inner-line permits & camping royalties",
      "Sub-zero extreme mountain dome tents & rated down sleeping bags",
      "Nutritious high-carb alpine meal plan designed for acclimatization",
      "Full safety suite: Oxygen cylinder, Gamow bag access, emergency stretchers",
    ],
    packingList: [
      "Rigid high-ankle waterproof trekking boots with Vibram soles",
      "Crampons / Microspikes (provided in season if required)",
      "Heavy down parka with minimum 700 fill power",
      "Thermal base layers, fleece mid-layers, and waterproof shell pants",
      "Category 4 mountaineering glacier glasses",
      "Trekking poles with snow baskets and 100L waterproof duffel / rucksack",
    ],
  },
  {
    id: 103,
    title: "Bedni Bugyal Alpine Meadow Track",
    subtitle: "Walk across Asia's largest velvety green meadow with grandstand vistas of Mt. Trishul.",
    slug: "bedni-bugyal-alpine-meadow-track",
    region: "Chamoli, Garhwal",
    startPoint: "Lohajung / Wan Village",
    endPoint: "Lohajung",
    durationDays: 5,
    durationNights: 4,
    altitudeFt: "11,540 ft",
    altitudeM: "3,517 m",
    difficulty: "Easy to Moderate",
    gradeColor: "amber",
    distanceKm: "28 km",
    bestSeason: "May – June (Lush Green Carpet) & Sept – Nov (Crystal Autumn Panoramas)",
    price: 10490,
    originalPrice: 14000,
    rating: 4.8,
    reviews: 198,
    image: bedniBugyalImg,
    category: "Velvet Bugyals (Meadows)",
    badge: "Asia's Finest Meadow",
    vibe: "Velvet Bugyals (Meadows)",
    tags: ["Asia's Largest Bugyal", "Mt. Trishul Sunrise", "Bedni Kund Lake", "Himalayan Wildflowers"],
    overview:
      "Bedni Bugyal is universally acclaimed as one of Asia's grandest and most picturesque high-altitude meadows. Spanning undulating waves of velvety green alpine turf that roll out towards the colossal massifs of Mt. Trishul (7,120m) and Nanda Ghunti (6,309m), this track is pure poetry for nature lovers. In the summer months, the bugyal is carpeted with thousands of wild alpine flowers around the sacred Bedni Kund lake, while autumn brings golden pastures beneath razor-sharp azure mountain skies.",
    itinerary: [
      {
        day: 1,
        title: "Rishikesh / Kathgodam to Lohajung (7,660 ft)",
        desc: "Scenic scenic mountain drive passing through Karnaprayag and Tharali. Check into mountain guesthouse in Lohajung, the historic gateway to Roopkund and Bedni.",
      },
      {
        day: 2,
        title: "Lohajung to Didna Village (8,040 ft)",
        desc: "Descend into the Neel Ganga river valley, crossing a rustic suspension bridge. Ascend through dense forests of oak and weeping rhododendrons to the idyllic traditional stone village of Didna.",
      },
      {
        day: 3,
        title: "Didna to Ali Bugyal & Bedni Bugyal (11,540 ft)",
        desc: "Steep climb through the mysterious Tolpani oak forest. Emerge suddenly onto the mind-boggling open meadows of Ali Bugyal, then traverse the ridge to Bedni Bugyal right before Mt. Trishul.",
      },
      {
        day: 4,
        title: "Bedni Kund Exploration & Sunset over Trishul",
        desc: "Morning walk to the sacred Bedni Kund. Marvel at the reflection of Trishul and Nanda Ghunti in the placid water. Watch the golden rays illuminate the alpine pasture at twilight.",
      },
      {
        day: 5,
        title: "Bedni Bugyal to Wan Village & Drive to Lohajung / Rishikesh",
        desc: "Descend through centuries-old cypress and walnut trees to the road-head at Wan village, followed by vehicle transfer back to Rishikesh.",
      },
    ],
    inclusions: [
      "Certified Wilderness First Responder Trek Leaders",
      "Spacious all-weather 3-man alpine dome tents (twin sharing) with foam mattresses",
      "Wholesome, fresh local vegetarian meals with hot evening soups",
      "Forest sanctuary entry permits and eco-conservation passes",
      "First aid medical kit with oximeter and oxygen canister",
    ],
    packingList: [
      "Comfortable broken-in trekking shoes with good traction",
      "Lightweight rain poncho or waterproof jacket",
      "Warm fleece jacket and windproof over-jacket",
      "Wide brim sun hat and UV protective sunglasses",
      "Trekking poles to support knee joints during downhill descents",
    ],
  },
  {
    id: 104,
    title: "Kuari Pass Winter & Ridge Track",
    subtitle: "The legendary Curzon Trail offering an awe-inspiring amphitheater view of Mt. Nanda Devi.",
    slug: "kuari-pass-ridge-track",
    region: "Chamoli, Joshimath",
    startPoint: "Joshimath / Dhak Village",
    endPoint: "Auli / Joshimath",
    durationDays: 6,
    durationNights: 5,
    altitudeFt: "12,516 ft",
    altitudeM: "3,815 m",
    difficulty: "Easy to Moderate",
    gradeColor: "cyan",
    distanceKm: "33 km",
    bestSeason: "Nov – April (Best Snow Ridge Trek) & May – June (Rhododendron Season)",
    price: 11990,
    originalPrice: 15500,
    rating: 4.9,
    reviews: 210,
    image: kuariPassImg,
    category: "Historic Ridge Passes",
    badge: "The Curzon Trail",
    vibe: "Historic Ridge Passes",
    tags: ["Lord Curzon Trail", "Mt. Nanda Devi Views", "Gorson Bugyal Snow", "Oak & Chestnut Canopies"],
    overview:
      "Commissioned in 1905 by Lord Curzon (former Viceroy of India), Kuari Pass ('The Curzon Trail') provides what many mountaineers regard as the most stunning mountain amphitheater in the world. As you stand atop the ridge at 12,516 ft, Mt. Nanda Devi (India's second highest mountain at 7,816m), Kamet (7,756m), Dronagiri, Hathi-Ghodi Parvat, and Chaukhamba feel close enough to touch. In winter, this transforms into one of the country's greatest snow ridge tracks.",
    itinerary: [
      {
        day: 1,
        title: "Rishikesh to Joshimath via Alaknanda Valley (6,150 ft)",
        desc: "A picturesque 9-hour mountain drive tracing the sacred Panch Prayag confluences (Devprayag, Rudraprayag, Karnaprayag, Nandaprayag, and Vishnuprayag). Evening briefing in Joshimath.",
      },
      {
        day: 2,
        title: "Joshimath to Dhak Village Drive & Trek to Gulling (9,600 ft)",
        desc: "Short drive to Dhak village. Ascend past step-farmed mountain villages and into fragrant oak and pine woods to the secluded clearing at Gulling camp.",
      },
      {
        day: 3,
        title: "Gulling to Khullara Campsite (11,100 ft)",
        desc: "A steady climb through pristine walnut and rhododendron forests that open up to the high alpine clearing at Khullara. Outstanding sunset views of Dronagiri and Hathi Parvat.",
      },
      {
        day: 4,
        title: "Summit Day: Khullara to Kuari Pass (12,516 ft) & back",
        desc: "Ridge trek across the windswept pass. Reach Kuari Pass to witness the gargantuan north face of Mt. Nanda Devi, Kamet, and Trishul stretching across the horizon in unmatched glory.",
      },
      {
        day: 5,
        title: "Khullara to Tali & Gorson Bugyal to Auli (8,500 ft)",
        desc: "Traverse high ridge trails across the endless snow plains of Gorson Bugyal, finishing at the famous ski slopes of Auli. Cable car or taxi down to Joshimath.",
      },
      {
        day: 6,
        title: "Joshimath to Rishikesh Departure",
        desc: "Morning departure from Joshimath back to Rishikesh / Haridwar with unforgettable Himalayan memories.",
      },
    ],
    inclusions: [
      "Qualified IMF & NIM Mountain Leaders with Local High-Altitude Guides",
      "Sub-zero all-weather tents, insulated foam mattresses & sleeping bags",
      "Nutritious high-altitude vegetarian meals cooked fresh at campsites",
      "Forest department permits, camping royalties & environmental cess",
      "Safety gear including pulse oximeter, medical oxygen, and first aid box",
    ],
    packingList: [
      "Warm waterproof trekking boots with firm ankle support and snow gaiters",
      "Thermal thermals (upper and lower), warm fleece and windproof outer layer",
      "Waterproof ski gloves + fleece inner gloves",
      "Balaclava and woolen beanie cap",
      "High UV sunglasses and high SPF 50 sunscreen",
    ],
  },
  {
    id: 105,
    title: "Nanda Devi Sanctuary Base Expedition",
    subtitle: "Trek into the mystical UNESCO Biosphere Reserve surrounding India's legendary goddess mountain.",
    slug: "nanda-devi-sanctuary-base-track",
    region: "Nanda Devi Biosphere Reserve, Chamoli",
    startPoint: "Lata Village / Joshimath",
    endPoint: "Lata Village",
    durationDays: 8,
    durationNights: 7,
    altitudeFt: "14,200 ft",
    altitudeM: "4,330 m",
    difficulty: "Challenging Expedition",
    gradeColor: "purple",
    distanceKm: "45 km",
    bestSeason: "May – June & Sept – Oct (UNESCO Sanctuary Window)",
    price: 19990,
    originalPrice: 25000,
    rating: 5.0,
    reviews: 130,
    image: nandaDeviImg,
    category: "Sanctuary Wilderness",
    badge: "UNESCO Biosphere",
    vibe: "Sanctuary Wilderness",
    tags: ["UNESCO World Heritage", "Goddess Mountain", "Dharansi Pass", "Virgin Himalayan Forests"],
    overview:
      "The Nanda Devi Sanctuary is steeped in deep mythological reverence and strict ecological preservation. Ringed by an impenetrable wall of over seventy colossal 6,000-meter peaks, this expedition takes you through the strictly regulated outer perimeter via Lata Kharak, Jhandi Dhar, and Dharansi Pass (14,200 ft). Walking along pristine birch ridges and glacial moraines, you stand directly before the mythic presence of Goddess Nanda Devi, accompanied by sightings of rare musk deer, bharal, and the elusive snow leopard.",
    itinerary: [
      {
        day: 1,
        title: "Rishikesh to Joshimath via Alaknanda Valley",
        desc: "Full day mountain journey to Joshimath. Complete registration and inner-line forest permit verifications with the Nanda Devi National Park authorities.",
      },
      {
        day: 2,
        title: "Joshimath to Lata Village Drive & Trek to Bhelta (9,100 ft)",
        desc: "Drive to the heritage Bhotia village of Lata. Begin steep ascent through ancient deodar and mixed fir forests to the intermediate campsite at Bhelta.",
      },
      {
        day: 3,
        title: "Bhelta to Lata Kharak High Ridge (12,140 ft)",
        desc: "Climb through the dense rhododendron canopy before emerging onto the stark, breathtaking high ridge of Lata Kharak with dramatic valley drops.",
      },
      {
        day: 4,
        title: "Acclimatization Day at Lata Kharak & Jhandi Dhar",
        desc: "Day hike to Jhandi Dhar viewpoint. Marvel at the sheer drop into the Rishi Ganga gorge and the colossal pyramid peaks of Dronagiri and Bethartoli.",
      },
      {
        day: 5,
        title: "Lata Kharak to Dharansi Pass & High Sanctuary Ridge (14,200 ft)",
        desc: "The most challenging day of the expedition. Navigate razor-thin ridge lines and steep boulder scrambles to Dharansi Pass for an ethereal view into the outer Nanda Devi Sanctuary.",
      },
      {
        day: 6,
        title: "Exploration along the Outer Sanctuary Perimeter",
        desc: "Immerse in the pristine silence of this strictly protected biosphere. Observe rare alpine flowers, Himalayan monal pheasants, and breathtaking glacial morphology.",
      },
      {
        day: 7,
        title: "Dharansi Pass Descent to Lata Village via Tolma",
        desc: "Gradual descent tracing back through the virgin birch forest and down to the idyllic mountain village of Tolma. Transfer to Joshimath hotel.",
      },
      {
        day: 8,
        title: "Joshimath to Rishikesh / Dehradun Departure",
        desc: "Scenic return drive down the Himalayas to Rishikesh, carrying the blessing of the holy mountain.",
      },
    ],
    inclusions: [
      "High-Altitude NIM Certified Expedition Leaders & Armed Eco-Guides",
      "Special Nanda Devi Biosphere Reserve Forest Permits & Entry Passports",
      "Four-season expedition geodesic dome tents & extreme sub-zero down sleeping bags",
      "High-nutrition high-altitude dietary meal plan prepared by mountain expedition cooks",
      "Comprehensive medical kit, emergency oxygen, satellite communication / radio setup",
    ],
    packingList: [
      "Rigid high-ankle mountaineering trek boots with crampon compatibility if needed",
      "Complete 4-layer thermal and expedition wind/waterproof technical garments",
      "Mountaineering trekking poles with shock-absorbing tips",
      "Heavy duty sub-zero mittens + waterproof outer gloves",
      "Glacier polarized glasses and high protective balaclava",
    ],
  },
];

