// Backend data for tours
import kedarnathImg from "../../assets/places/kedarnath.png";
import govindghatImg from "../../assets/places/Govindghat.jpg";
import rishikeshImg from "../../assets/places/rishikesh.jpeg";
import nainitalImg from "../../assets/places/naintal.jpeg";
import auliImg from "../../assets/places/auli.webp";
import almoraImg from "../../assets/places/almora.jpeg";
import mussoorieImg from "../../assets/places/mussoire.jpg";
import trekkingImg from "../../assets/adventurs/tracking.jpg";
import raftingImg from "../../assets/adventurs/river-rafting.webp";
import wildlifeImg from "../../assets/adventurs/wildlife.jpg";        
import yogaImg from "../../assets/adventurs/yoga.jpg";
import roadtripImg from "../../assets/adventurs/roadtrip.jpg";
import campingImg from "../../assets/adventurs/camping.jpeg";
import skydivingImg from "../../assets/adventurs/sky-diving.jpeg";
import banjijumpingImg from "../../assets/adventurs/bungee-jumping.jpg";

const toursData = [
  {
    id: 1,
    title: "7-Day Char Dham Yatra (Deluxe)",
    destination: "Uttarakhand: Kedarnath, Badrinath",
    duration: 7,
    style: "Pilgrimage",
    rating: 4.8,
    reviews: 210,
    price: 34990,
    originalPrice: 40000,
    onSale: true,
    icon: "ph-mountain",
    category: "Pilgrimage",
    image: kedarnathImg, // image added
  },
  {
    id: 2,
    title: "5-Day Valley of Flowers Trek",
    destination: "Uttarakhand: Govindghat, Hemkund",
    duration: 5,
    style: "Trekking",
    rating: 5.0,
    reviews: 188,
    price: 15500,
    originalPrice: null,
    onSale: false,
    icon: "ph-flower-lotus",
    category: "Trekking",
    image: govindghatImg,
  },
  {
    id: 3,
    title: "3-Day Rishikesh Adventure Camp",
    destination: "Uttarakhand: Rishikesh, Shivpuri",
    duration: 3,
    style: "Adventure Sports",
    rating: 4.7,
    reviews: 310,
    price: 9990,
    originalPrice: null,
    onSale: false,
    icon: "ph-boat",
    category: "Adventure",
    image: rishikeshImg,
  },
  {
    id: 4,
    title: "4-Day Nainital & Kumaon Family Tour",
    destination: "Uttarakhand: Nainital, Bhimtal",
    duration: 4,
    style: "Family",
    rating: 4.6,
    reviews: 95,
    price: 18000,
    originalPrice: 20000,
    onSale: true,
    icon: "ph-users-three",
    category: "Family",
    image: nainitalImg,
  },
  {
    id: 5,
    title: "6-Day Auli Snow & Trekking Expedition",
    destination: "Uttarakhand: Joshimath, Auli",
    duration: 6,
    style: "Winter Sports",
    rating: 4.9,
    reviews: 150,
    price: 28000,
    originalPrice: null,
    onSale: false,
    icon: "ph-ski",
    category: "Trekking",
    image: auliImg,
  },
  {
    id: 6,
    title: "Almora Kumaon Hills Adventure",
    destination: "Uttarakhand: Almora, Kumaon",
    duration: 4,
    style: "Sightseeing",
    rating: 4.4,
    reviews: 75,
    price: 19900,
    originalPrice: 21000,
    onSale: false,
    icon: "ph-tree-evergreen",
    category: "Kumaon",
    image: almoraImg,
  },
  {
    id: 7,
    title: "Nainital Lake District Trip",
    destination: "Uttarakhand: Nainital, Bhimtal",
    duration: 3,
    style: "Family",
    rating: 4.6,
    reviews: 120,
    price: 14900,
    originalPrice: null,
    onSale: true,
    icon: "ph-drop",
    category: "Kumaon",
    image: nainitalImg,
  },
  {
    id: 8,
    title: "Ganga Rishikesh White Water Rafting",
    destination: "Uttarakhand: Rishikesh, Rafting",
    duration: 2,
    style: "Adventure Sports",
    rating: 4.9,
    reviews: 450,
    price: 29900,
    originalPrice: null,
    onSale: false,
    icon: "ph-tent",
    category: "Adventure",
    image: rishikeshImg,
  },
  {
    id: 9,
    title: "Mussoorie Queen of Hills Scenic Tour",
    destination: "Uttarakhand: Mussoorie, Dehradun",
    duration: 5,
    style: "Family",
    rating: 4.5,
    reviews: 105,
    price: 24900,
    originalPrice: 26000,
    onSale: false,
    icon: "ph-cable-car",
    category: "Family",
    image: mussoorieImg,
  },
];

export default toursData;

// src/components/Backend/BackenData.jsx

export const ADVENTURE_STYLES = [
  {
    id: 1,
    slug: "trekking-and-hiking",
    title: "Trekking & Hiking",
    badge: "Highest Himalayan Trails",
    tagline: "Scale snow-crested summits, discover crystal glacial lakes, and walk ancient shepherd paths.",
    description:
      "Scale iconic Himalayan peaks, discover hidden high-altitude lakes, and traverse lush forests.",
    overview:
      "Uttarakhand is the legendary cradle of Indian Himalayan trekking. Spanning the towering Garhwal and Kumaon ranges, each trail weaves breathtaking wilderness with mythological folklore. Whether you are stepping onto the crisp snows of Kedarkantha Summit, walking through the floral paradise of Valley of Flowers, or traversing the mystical trails of Har Ki Dun beneath the Swargarohini peaks, you will witness dramatic mountain vistas and authentic Himalayan hospitality.",
    icon: "ph-mountains-fill",
    example: "Kedarkantha, Valley of Flowers, Har Ki Dun",
    color: "text-emerald-500",
    themeBg: "from-emerald-600 to-teal-800",
    accentBorder: "border-emerald-500",
    imageUrl: trekkingImg,
    stats: {
      difficulty: "Moderate to Challenging",
      bestSeason: "March – June & September – December",
      duration: "3 – 8 Days",
      altitude: "Up to 14,100 ft (4,300m)",
      idealFor: "Trekkers, Nature Lovers, Solos & Groups",
    },
    highlights: [
      {
        icon: "ph-mountain-fill",
        title: "Iconic Himalayan Summits",
        desc: "Reach legendary summits like Kedarkantha (12,500 ft) and Chandrashila (13,100 ft) with 360-degree panoramas of Nanda Devi, Chaukhamba, and Trishul.",
      },
      {
        icon: "ph-flower-lotus-fill",
        title: "UNESCO World Heritage Flora",
        desc: "Wander across the Valley of Flowers carpeted with over 500 varieties of endemic alpine wildflowers blooming between July and September.",
      },
      {
        icon: "ph-tent-fill",
        title: "Pristine Alpine Camping",
        desc: "Sleep under billions of stars in insulated four-season dome tents pitched on velvet green Bugyals (high-altitude meadows).",
      },
      {
        icon: "ph-shield-check-fill",
        title: "Certified Mountain Leadership",
        desc: "Every trek is led by IMF & Nehru Institute of Mountaineering (NIM) certified trek leaders equipped with emergency oxygen and first-aid kits.",
      },
    ],
    destinations: [
      {
        name: "Kedarkantha Summit Trek",
        altitude: "12,500 ft",
        duration: "5 Days / 4 Nights",
        difficulty: "Easy - Moderate",
        tag: "Best Winter Snow Trek",
        desc: "A mesmerizing trail through pine and oak forests, frozen Juda Ka Talab lake, and an exhilarating sunrise push to the 360° summit.",
      },
      {
        name: "Valley of Flowers & Hemkund Sahib",
        altitude: "14,100 ft",
        duration: "6 Days / 5 Nights",
        difficulty: "Moderate",
        tag: "UNESCO World Heritage",
        desc: "Traverse a vibrant valley of wild lilies, blue poppies, and orchids, leading to the world's highest sacred glacier lake at Hemkund Sahib.",
      },
      {
        name: "Chopta - Tungnath - Chandrashila",
        altitude: "13,100 ft",
        duration: "4 Days / 3 Nights",
        difficulty: "Moderate",
        tag: "Highest Shiva Temple",
        desc: "Hike through the rhododendron-rich meadows of Chopta (Mini Switzerland) up to Tungnath temple and the spectacular Chandrashila peak.",
      },
      {
        name: "Har Ki Dun (Valley of Gods)",
        altitude: "11,700 ft",
        duration: "7 Days / 6 Nights",
        difficulty: "Moderate",
        tag: "Ancient Mythological Trail",
        desc: "Cradle-shaped valley nestled beneath the Swargarohini peaks, dotted with 1,000-year-old carved wooden villages of Osla and Gangad.",
      },
    ],
    included: [
      "IMF & NIM Certified Trek Leaders & Support Crew",
      "High-grade Alpine Dome Tents, Sleeping Bags & Insulated Mattresses",
      "All Vegetarian Himalayan Meals (Breakfast, Packed Lunch, Evening Snacks, Hot Dinner)",
      "Forest Entry Permits, Eco Camping Fees & Camping Charges",
      "Medical Safety Kit, Pulse Oximeter, Oxygen Cylinders & Stretcher",
      "Mule / Porter Logistics for Common Camping Equipment",
    ],
    packingList: [
      "Sturdy, waterproof trekking shoes with deep ankle support",
      "3-layer clothing: Thermal base, fleece mid-layer, and waterproof down jacket",
      "40L-60L ergonomic backpack with rain cover",
      "Quick-dry trek pants, thermal innerwear, and moisture-wicking tees",
      "UV protection sunglasses (Category 3 or 4) and Sunscreen SPF 50+",
      "Trekking poles, LED headlamp with extra batteries, and personal water bladder",
    ],
    faqs: [
      {
        q: "Do I need prior trekking experience?",
        a: "No, popular treks like Kedarkantha, Chopta-Chandrashila, and Valley of Flowers are very beginner-friendly for anyone with basic cardiovascular fitness and enthusiasm.",
      },
      {
        q: "What is the policy for Acute Mountain Sickness (AMS)?",
        a: "Our itineraries are meticulously designed with acclimatization days. Trek leaders monitor blood oxygen levels twice daily and carry medical oxygen cylinders and first aid.",
      },
      {
        q: "Are toilet facilities available during the trek?",
        a: "Yes, dry pit toilet tents with hygienic toilet seats and sawdust are set up at every campsite in full accordance with Leave No Trace environmental guidelines.",
      },
      {
        q: "What kind of food is served on high altitude treks?",
        a: "Fresh, warm, high-carbohydrate vegetarian meals prepared by mountain cooks, including dal, rice, rotis, sabzi, eggs (where preferred), warm soups, and hot tea.",
      },
    ],
    relatedTourIds: [2, 5],
  },
  {
    id: 2,
    slug: "aquatic-adventures",
    title: "Aquatic Adventures",
    badge: "Ultimate River Thrills",
    tagline: "Conquer roaring Grade III-IV+ Ganges rapids, leap from cliffs, and feel the surging Himalayan rush.",
    description:
      "Conquer the mighty Ganges with white-water rafting, or try kayaking, canyoning near Rishikesh.",
    overview:
      "Fed by the melting glaciers of Bhagirathi and Alaknanda, Uttarakhand's roaring rivers carve some of the world's most thrilling white-water courses. Rishikesh stands proudly as the white-water capital of India. Navigate legendary rapids such as 'Roller Coaster', 'Golf Course', 'Three Blind Mice', and 'The Wall' with International Rafting Federation (IRF) certified captains, or leap from 30-foot granite cliffs into crystal-clear turquoise pools.",
    icon: "ph-waves-fill",
    example: "Rishikesh Rafting, Kayaking in Shivpuri",
    color: "text-blue-500",
    themeBg: "from-blue-600 to-cyan-800",
    accentBorder: "border-blue-500",
    imageUrl: raftingImg,
    stats: {
      difficulty: "Beginner to Thrill Seeker",
      bestSeason: "September – June",
      duration: "1 – 4 Days",
      altitude: "1,200 – 2,500 ft",
      idealFor: "Adrenaline Junkies, Friends & Adventure Lovers",
    },
    highlights: [
      {
        icon: "ph-waves-fill",
        title: "Grade III to IV+ White Water",
        desc: "Paddle through furious emerald waves and technical hydro-drops with seasoned river captains.",
      },
      {
        icon: "ph-arrow-up-right-bold",
        title: "Cliff Jumping & Body Surfing",
        desc: "Experience zero-gravity cliff jumps from 25-30 ft natural rock ledges and float safely in deep river channels.",
      },
      {
        icon: "ph-tent-fill",
        title: "Riverside Sand Beach Camping",
        desc: "Stay in luxury riverside safari camps on Shivpuri's silvery beaches with beach volleyball and evening bonfires.",
      },
      {
        icon: "ph-drop-fill",
        title: "Waterfall Rappelling & Canyoning",
        desc: "Rappel down roaring natural cascades in the secluded Neer Garh and Patna gorges.",
      },
    ],
    destinations: [
      {
        name: "Marine Drive to Rishikesh (26 km)",
        altitude: "1,400 ft",
        duration: "Full Day / 4-5 Hours Rafting",
        difficulty: "Grade III - IV+",
        tag: "Ultimate Adrenaline Rush",
        desc: "Runs through famous rapids: Three Blind Mice, Cross Fire, Roller Coaster, and Golf Course with cliff jumping.",
      },
      {
        name: "Shivpuri to NIM Beach (16 km)",
        altitude: "1,350 ft",
        duration: "Half Day / 3 Hours",
        difficulty: "Grade II - III+",
        tag: "The Classic Favorite",
        desc: "The most popular stretch in India, ideal for beginners and friends looking for thrilling wave-trains.",
      },
      {
        name: "Tons River Expedition (Mori)",
        altitude: "3,800 ft",
        duration: "4 Days Expedition",
        difficulty: "Grade IV - V",
        tag: "Hardcore Expedition",
        desc: "Known as India's most technical and ferocious river, rushing through deep Garhwal ravines.",
      },
      {
        name: "Brahmapuri to Rishikesh (9 km)",
        altitude: "1,250 ft",
        duration: "2 Hours",
        difficulty: "Grade I - II",
        tag: "Family & Beginners",
        desc: "Gentle rolling rapids with calm stretches for floating, swimming, and scenic mountain views.",
      },
    ],
    included: [
      "IRF-Certified River Guides, Safety Kayakers & Rescue Teams",
      "High-grade Inflatable Rafts, Paddles, Life Jackets & Helmets (CE/ISO Approved)",
      "Cliff Jumping and Body Surfing gear & guidance",
      "All Transport from Rishikesh Base to Launch Points",
      "Riverside Camp Accommodation with Attached Bath & Buffet Meals (for camp packages)",
      "First Aid Equipment & Safety Briefing",
    ],
    packingList: [
      "Quick-drying synthetic swimwear / nylon shorts and T-shirts",
      "River footwear: Strapped sandals or water shoes with non-slip grip",
      "Waterproof dry bag or waterproof phone pouch",
      "Extra change of warm clothes for post-rafting change",
      "High SPF waterproof sunscreen and sunglasses with floating strap",
      "Quick-dry microfiber towel",
    ],
    faqs: [
      {
        q: "Is swimming ability mandatory for white water rafting?",
        a: "No! High-flotation CE-certified life jackets are provided that keep you afloat even if you cannot swim, and every raft is manned by licensed guides.",
      },
      {
        q: "What is the age limit for rafting?",
        a: "For standard stretches (16km Shivpuri), the minimum age is 14 years and maximum recommended age is 65 years in good physical health.",
      },
      {
        q: "When is the rafting season closed?",
        a: "Rafting in Uttarakhand is closed during the monsoon months (July 1 to mid-September) for safety due to high water discharge.",
      },
      {
        q: "Are cameras allowed on the raft?",
        a: "Action cameras (GoPro) with helmet mounts are allowed. Most guides also carry waterproof dry bags for small personal items.",
      },
    ],
    relatedTourIds: [8, 3],
  },
  {
    id: 3,
    slug: "wildlife-safari",
    title: "Wildlife Safari",
    badge: "Untamed Foothills",
    tagline: "Track royal Bengal tigers, wild elephant herds, and over 600 exotic bird species across dense sal jungles.",
    description:
      "Explore the biodiversity of the Himalayan foothills. Spot tigers, elephants, and leopards in national parks.",
    overview:
      "Cradled where the mighty Himalayas meet the Terai lowlands, Uttarakhand preserves some of Asia's most pristine wilderness. Jim Corbett National Park—India's first national park established in 1936—holds the world's highest tiger density. Venture in open 4x4 gypsies through dense sal canopies and expansive grasslands (Chours) to watch wild elephant herds bathe in the Ramganga River, spot leopards, sloth bears, marsh crocodiles, and hundreds of vibrant bird species.",
    icon: "ph-paw-print-fill",
    example: "Jim Corbett National Park, Rajaji Reserve",
    color: "text-amber-500",
    themeBg: "from-amber-700 to-emerald-900",
    accentBorder: "border-amber-500",
    imageUrl: wildlifeImg,
    stats: {
      difficulty: "Easy / Family Friendly",
      bestSeason: "November – June (Dhikala zone opens Nov 15)",
      duration: "2 – 5 Days",
      altitude: "1,000 – 4,000 ft",
      idealFor: "Wildlife Photographers, Families, Birders",
    },
    highlights: [
      {
        icon: "ph-paw-print-fill",
        title: "Royal Bengal Tiger Tracking",
        desc: "Explore core tiger zones (Dhikala, Bijrani, Jhirna) with veteran naturalists reading pugmarks and alarm calls.",
      },
      {
        icon: "ph-binoculars-fill",
        title: "600+ Avian Species Haven",
        desc: "Spot Great Pied Hornbills, Pallas's Fish Eagles, Collared Falconets, and Crested Kingfishers.",
      },
      {
        icon: "ph-jeep-fill",
        title: "Exclusive 4x4 Gypsy Safaris",
        desc: "Open top morning and evening safaris deep through grasslands, riverbeds, and century-old sal woodlands.",
      },
      {
        icon: "ph-tree-evergreen-fill",
        title: "Historic British-Era Forest Lodges",
        desc: "Experience staying inside the core zone in heritage forest rest houses surrounded by the nocturnal wild.",
      },
    ],
    destinations: [
      {
        name: "Jim Corbett National Park (Dhikala & Bijrani)",
        altitude: "1,200 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Highest Tiger Density",
        desc: "The crown jewel of Corbett boasting sweeping Ramganga reservoir views, vast elephant herds, and tiger sightings.",
      },
      {
        name: "Rajaji Tiger Reserve (Chilla & Motichur)",
        altitude: "1,100 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Easy",
        tag: "Elephant Corridors",
        desc: "Nestled along the Shivalik range, renowned for grand wild Asian tuskers, leopards, and 315 bird species.",
      },
      {
        name: "Binsar Wildlife Sanctuary",
        altitude: "7,900 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy Walking",
        tag: "High Altitude Birding",
        desc: "Dense oak and rhododendron forest with zero vehicular noise and 300km Himalayan snow-peak panoramas.",
      },
      {
        name: "Asan Wetland Conservation Reserve",
        altitude: "1,300 ft",
        duration: "Day Excursion",
        difficulty: "Easy",
        tag: "Ramsar Wetland Site",
        desc: "Vital winter stopover for thousands of migratory waterfowl traveling across the trans-Himalayan flyway.",
      },
    ],
    included: [
      "Authorized Open 4x4 Gypsy Vehicle & Forest Driver",
      "Mandatory Government Forest Naturalist / Guide",
      "National Park Entry Permits, Vehicle Road Taxes & Camera Fees",
      "Resort / Jungle Lodge Stays with All Meals",
      "Pick-up and Drop from Ramnagar / Haridwar Railway Station",
    ],
    packingList: [
      "Earthy clothing (khaki, olive, brown, dark green; avoid bright red/yellow)",
      "Warm fleece jacket, gloves, and muffler for chilly morning open-gypsy drives",
      "High-magnification binoculars (8x42 or 10x42)",
      "DSLR / Mirrorless camera with 200mm+ telephoto lens",
      "Dust mask or scarf to protect against dry forest dust",
      "Government photo ID (Passport / Aadhaar) matching safari permit",
    ],
    faqs: [
      {
        q: "How early should I book Corbett safari permits?",
        a: "Safari permits for core zones like Dhikala and Bijrani open 45 days in advance for Indian citizens and 90 days for foreigners. Booking early is strongly advised.",
      },
      {
        q: "Are safaris safe for young children and elderly travelers?",
        a: "Yes! Safaris are conducted in private 4x4 gypsies under strict forest department guidelines and are suitable for all age groups.",
      },
      {
        q: "Which safari zone offers the best chance of spotting a tiger?",
        a: "Dhikala is famous for the highest visibility across open grasslands. Bijrani and Jhirna also have exceptionally high tiger and leopard encounter rates.",
      },
      {
        q: "Is walking allowed inside the national park?",
        a: "Walking is strictly prohibited inside Jim Corbett core zones. Walking safaris and nature trails are permitted only in Binsar Wildlife Sanctuary and buffer eco-tourism zones.",
      },
    ],
    relatedTourIds: [4, 6],
  },
  {
    id: 4,
    slug: "pilgrimage-and-spirituality",
    title: "Pilgrimage & Spirituality",
    badge: "Sacred Land of the Gods",
    tagline: "Journey through Devbhoomi to the sacred shrines of Char Dham, ancient Panch Kedar, and divine ashrams.",
    description:
      "Journey to the holy shrines of Char Dham, meditate in Rishikesh ashrams, and seek blessings.",
    overview:
      "Since Vedic antiquity, Uttarakhand has been revered as Devbhoomi—the Sacred Abode of the Gods. Here the holy rivers Ganga and Yamuna descend from heavenly glaciers, and sacred shrines stand enveloped by colossal snow peaks. Fulfill the lifetime dream of completing the Char Dham Yatra (Yamunotri, Gangotri, Kedarnath, and Badrinath), meditate in Himalayan caves where the sages discovered yoga, and immerse in the celestial evening Ganga Aarti at Haridwar.",
    icon: "ph-house-line-fill",
    example: "Char Dham Yatra, Haridwar Ganga Aarti",
    color: "text-orange-500",
    themeBg: "from-amber-600 to-orange-800",
    accentBorder: "border-orange-500",
    imageUrl: kedarnathImg,
    stats: {
      difficulty: "Moderate",
      bestSeason: "May – June & September – November",
      duration: "4 – 12 Days",
      altitude: "Up to 11,755 ft (3,584m)",
      idealFor: "Devotees, Families, Spiritual Seekers",
    },
    highlights: [
      {
        icon: "ph-house-line-fill",
        title: "Sacred Char Dham Yatra",
        desc: "Complete the soul-cleansing Himalayan pilgrimage to Yamunotri, Gangotri, Kedarnath, and Badrinath with VIP darshan assistance.",
      },
      {
        icon: "ph-fire-fill",
        title: "Twilight Ganga Aarti",
        desc: "Witness thousands of glowing brass lamps, fragrant incense, and Vedic hymns at Har Ki Pauri and Parmarth Niketan.",
      },
      {
        icon: "ph-path-fill",
        title: "Panch Prayag Holy Confluences",
        desc: "Visit the five sacred river confluences (Devprayag, Rudraprayag, Karnaprayag, Nandaprayag, Vishnuprayag).",
      },
      {
        icon: "ph-sparkle-fill",
        title: "Heli-Yatra & Priority Darshan",
        desc: "Option for Kedarnath helicopter shuttle services from Phata / Guptkashi and pre-booked biometric passes.",
      },
    ],
    destinations: [
      {
        name: "Kedarnath Jyotirlinga (3,584m)",
        altitude: "11,755 ft",
        duration: "3-4 Days Excursion",
        difficulty: "Moderate",
        tag: "Highest of 12 Jyotirlingas",
        desc: "Nestled against the colossal Kedarnath peak, revered by millions as the eternal dwelling of Lord Shiva.",
      },
      {
        name: "Badrinath Dham (3,133m)",
        altitude: "10,279 ft",
        duration: "2-3 Days Excursion",
        difficulty: "Easy (Road Access)",
        tag: "Vaikuntha on Earth",
        desc: "The sacred black stone shrine of Lord Badri Vishal, guarded by the Nar and Narayan mountains beside the hot Tapt Kund springs.",
      },
      {
        name: "Gangotri & Yamunotri Dhams",
        altitude: "10,200 ft",
        duration: "4 Days Excursion",
        difficulty: "Moderate",
        tag: "Cradle of Sacred Rivers",
        desc: "The pristine high-altitude sources of the two holiest rivers of India flowing through dramatic granite canyons.",
      },
      {
        name: "Haridwar & Rishikesh Ghats",
        altitude: "1,050 ft",
        duration: "2-3 Days",
        difficulty: "Easy",
        tag: "Spiritual Gateways",
        desc: "Century-old temples, holy snan ghats, ashrams, and the legendary evening Ganga Aarti.",
      },
    ],
    included: [
      "AC Vehicle for all Sightseeing & Transfers across Mountain Routes",
      "Clean Handpicked Deluxe Hotel & Camp Stays with Geyser Facilities",
      "Pure Vegetarian Breakfast & Dinner (Satvik / Jain Options Available)",
      "Mandatory Biometric Registration & Yatra Pass Assistance",
      "Experienced Mountain Chauffeur & 24/7 Ground Support Team",
    ],
    packingList: [
      "Warm woolens: Thermals, heavy fleece jacket, woolen cap, and gloves",
      "Comfortable walking shoes with good grip for Kedarnath/Yamunotri treks",
      "Rainwear: Raincoat, umbrella, or waterproof poncho",
      "Personal medical kit: Altitude sickness pills, pain relief, glucose, and band-aids",
      "Power bank and cash (ATMs in high mountain sectors are often out of cash)",
      "Aadhaar Card / Government photo ID & Yatra Registration slip",
    ],
    faqs: [
      {
        q: "What is the best way to travel to Kedarnath?",
        a: "You can either trek the scenic 16 km trail from Gaurikund on foot, hire a pony/palanquin (palki), or take a 7-minute helicopter shuttle from Guptkashi, Phata, or Sersi.",
      },
      {
        q: "When do the Char Dham temple portals open and close?",
        a: "The portals open around Akshaya Tritiya (late April/early May) and close shortly after Diwali/Bhai Dooj in November for the winter period.",
      },
      {
        q: "Is medical certification required for the yatra?",
        a: "Basic health registration is mandatory. Senior citizens and those with heart conditions are advised to consult a physician and carry prescribed medications.",
      },
    ],
    relatedTourIds: [1, 2],
  },
  {
    id: 5,
    slug: "culture-and-heritage",
    title: "Culture & Heritage",
    badge: "Timeless Mountain Traditions",
    tagline: "Immerse in ancient stone-and-cedar architecture, living folklore, Kumaoni Aipan art, and local gastronomy.",
    description:
      "Immerse yourself in Kumaoni and Garhwali cultures. Visit centuries-old temples and enjoy local cuisine.",
    overview:
      "The twin mountain kingdoms of Garhwal and Kumaon hold a vibrant heritage woven over centuries. Walk cobblestone pathways through Almora's 500-year-old bazaar, admire 1,000-year-old stone temple carvings at Jageshwar nestled amidst ancient deodar forests, learn traditional red-and-white Aipan folk painting, and savor organic Pahadi culinary delicacies like Bhatt ki Churkani and Singori while residing in restored heritage village homestays.",
    icon: "ph-handshake-fill",
    example: "Almora, Kausani, Local Homestays",
    color: "text-purple-500",
    themeBg: "from-purple-700 to-indigo-900",
    accentBorder: "border-purple-500",
    imageUrl: almoraImg,
    stats: {
      difficulty: "Easy / Leisure",
      bestSeason: "All 12 Months",
      duration: "3 – 7 Days",
      altitude: "4,000 – 7,500 ft",
      idealFor: "Culture Lovers, Families, Explorers",
    },
    highlights: [
      {
        icon: "ph-house-line-fill",
        title: "Traditional Kath-Kuni Homestays",
        desc: "Stay in heritage stone-and-deodar dwellings, sharing meals with warm local mountain families.",
      },
      {
        icon: "ph-paint-brush-broad-fill",
        title: "Hands-on Aipan Art Workshops",
        desc: "Learn sacred geometric floor and wall art using red clay (Geru) and ground rice paste.",
      },
      {
        icon: "ph-bank-fill",
        title: "Ancient Stone Temple Clusters",
        desc: "Explore Jageshwar Dham's 124 monolithic stone shrines dating from the 7th to 12th centuries.",
      },
      {
        icon: "ph-bowl-food-fill",
        title: "Authentic Pahadi Culinary Feasts",
        desc: "Savor Kafuli, Chainsoo, Mandua rotis, Jhangora kheer, and sweet Bal Mithai.",
      },
    ],
    destinations: [
      {
        name: "Jageshwar Dham & Almora Heritage",
        altitude: "6,200 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Archaeological Marvel",
        desc: "Surrounded by towering deodars, Jageshwar is one of India's most mystical ancient Shiva complexes.",
      },
      {
        name: "Kausani & Baijnath Valley",
        altitude: "6,200 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Switzerland of India",
        desc: "Panoramic 300km vistas of Nanda Devi and Trishul peaks, tea gardens, and 12th-century river temples.",
      },
      {
        name: "Mana Village (First Village of India)",
        altitude: "10,500 ft",
        duration: "Day Excursion from Badrinath",
        difficulty: "Easy Walk",
        tag: "Indo-Tibetan Border Heritage",
        desc: "Ancient Bhotia tribal village famous for handmade woolens, Vyas Gufa, and the dramatic Bhim Pul stone bridge.",
      },
      {
        name: "Lansdowne & Pauri Garhwal",
        altitude: "5,600 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy",
        tag: "Colonial & Folk History",
        desc: "Pristine pine forests, heritage churches, and panoramic views of the western Garhwal range.",
      },
    ],
    included: [
      "Authentic Heritage Homestay / Boutique Hotel Stays",
      "Traditional Kumaoni & Garhwali Breakfasts and Dinners",
      "Guided Walking Tours with Local Heritage Experts",
      "Aipan Folk Art Workshop & Local Craft Interactions",
      "Private Vehicle Transport with Experienced Local Chauffeur",
    ],
    packingList: [
      "Comfortable walking shoes for village strolls and cobbled markets",
      "Warm layers (sweaters / jackets) as mountain evenings can be cool",
      "Camera for capturing intricate temple carvings and village portraits",
      "Modest clothing for visiting revered temple complexes",
      "Eco-friendly reusable water bottle and shopping bag for local handicrafts",
    ],
    faqs: [
      {
        q: "What is special about Uttarakhand's village homestays?",
        a: "They offer an authentic glimpse into mountain life. You eat organic farm-to-table food, sleep in century-old timber homes, and support sustainable local village economies.",
      },
      {
        q: "Can children and seniors participate comfortably?",
        a: "Absolutely! Culture and heritage tours involve relaxed sightseeing, scenic road journeys, and gentle walks suitable for all generations.",
      },
    ],
    relatedTourIds: [6, 7, 4],
  },
  {
    id: 6,
    slug: "wellness-and-yoga-retreats",
    title: "Wellness & Yoga Retreats",
    badge: "Mindful Himalayan Awakening",
    tagline: "Harmonize your inner self in the world capital of Yoga with authentic Ayurveda, meditation, and detox.",
    description:
      "Find peace and rejuvenation in the lap of the mountains with yoga, meditation, and detox programs.",
    overview:
      "Where the sacred river Ganga flows out of the pristine Himalayas, surrounded by tranquil wooded foothills, lies Rishikesh—the Yoga Capital of the World. Disconnect from digital overwhelm and step into an oasis of mindfulness. Greet the dawn with Ganga-side pranayama and asana practices, nourish your body with wholesome satvik Ayurvedic nutrition, and experience deeply restorative sound baths and meditation guided by Himalayan masters.",
    icon: "ph-leaf-fill",
    example: "Rishikesh Yoga Schools, Wellness Centers",
    color: "text-rose-500",
    themeBg: "from-rose-600 to-pink-900",
    accentBorder: "border-rose-500",
    imageUrl: yogaImg,
    stats: {
      difficulty: "All Levels / Restorative",
      bestSeason: "September – May",
      duration: "3 – 14 Days",
      altitude: "1,200 – 5,000 ft",
      idealFor: "Solo Seekers, Couples, Wellness Enthusiasts",
    },
    highlights: [
      {
        icon: "ph-leaf-fill",
        title: "Daily Hatha & Ashtanga Yoga",
        desc: "Morning and sunset sessions overlooking the Ganga led by certified master yogis.",
      },
      {
        icon: "ph-heart-fill",
        title: "Ayurvedic Pulse Assessment & Abhyanga",
        desc: "Personalized dosha diagnosis and therapeutic warm herbal oil massages for deep detox.",
      },
      {
        icon: "ph-bell-ringing-fill",
        title: "Tibetan Sound Healing & Meditation",
        desc: "Harmonic sound bath frequencies designed to release deep-seated mental stress and anxiety.",
      },
      {
        icon: "ph-sun-dim-fill",
        title: "Organic Satvik & Detox Cuisine",
        desc: "Wholesome, freshly prepared farm-to-table Ayurvedic vegetarian cuisine that restores vitality.",
      },
    ],
    destinations: [
      {
        name: "Rishikesh Yoga Ashrams (Tapovan & Swarg Ashram)",
        altitude: "1,200 ft",
        duration: "5 to 14 Days",
        difficulty: "Gentle",
        tag: "World Yoga Capital",
        desc: "Legendary spiritual hub on the banks of the emerald Ganges, dotted with centuries-old yoga schools.",
      },
      {
        name: "Narendra Nagar Himalayan Foothills",
        altitude: "3,300 ft",
        duration: "3 to 7 Days",
        difficulty: "Luxury Restorative",
        tag: "Luxury Wellness Retreats",
        desc: "Secluded palatial estates offering world-renowned spa therapies, hydrotherapy, and panoramic valley views.",
      },
      {
        name: "Ranikhet & Kumaon Forest Sanctuaries",
        altitude: "6,000 ft",
        duration: "4 to 7 Days",
        difficulty: "Gentle",
        tag: "Forest Bathing & Silence",
        desc: "Meditate surrounded by towering pine and deodar forests with zero traffic and pure mountain prana.",
      },
    ],
    included: [
      "Serene Ashram or Boutique Wellness Resort Accommodation",
      "Two Daily Yoga & Guided Pranayama / Meditation Sessions",
      "Complete Satvik / Organic Ayurvedic Meals & Herbal Teas",
      "Doctor Consultation & Personalized Dosha Analysis",
      "Sound Healing Session & Ganga Ghat Evening Meditation",
    ],
    packingList: [
      "Comfortable, breathable cotton or linen yoga wear (white/light colors preferred)",
      "Personal yoga mat or travel mat towel",
      "Warm shawl or light blanket for early morning outdoor meditation",
      "Journal and pen for reflective journaling and insights",
      "Slip-on shoes / sandals for easy removal at ashrams and yoga halls",
    ],
    faqs: [
      {
        q: "I am a complete beginner to yoga. Can I join?",
        a: "Yes! All retreats accommodate beginners as well as seasoned practitioners. Instructors offer modifications to ensure comfort and safety.",
      },
      {
        q: "What is a Satvik diet?",
        a: "A Satvik diet emphasizes freshly cooked, seasonal, pure vegetarian foods prepared with minimal oil and spices, promoting lightness, clarity, and vitality.",
      },
    ],
    relatedTourIds: [3, 1],
  },
  {
    id: 7,
    slug: "motorcycle-and-road-trips",
    title: "Motorcycle & Road Trips",
    badge: "Open Road Mountain Freedom",
    tagline: "Ride legendary mountain asphalt, conquer hair-raising switchbacks, and witness untamed Himalayan grandeur.",
    description:
      "Experience the thrill of riding through challenging mountain passes and scenic highways on a guided bike tour.",
    overview:
      "Few thrills compare to revving an engine along the sweeping mountain curves of Uttarakhand. Trace the thunderous rivers along the all-weather Char Dham Highway, climb steep hairpin switchbacks to misty colonial hill stations, and cross soaring passes leading toward the Tibetan border. Accompanied by a dedicated support vehicle, experienced mechanics, and premier Royal Enfield Himalayan machines, you ride with absolute confidence and unfiltered freedom.",
    icon: "ph-motorcycle-fill",
    example: "Badrinath Road Trip, Remote Routes",
    color: "text-red-500",
    themeBg: "from-red-600 to-rose-900",
    accentBorder: "border-red-500",
    imageUrl: roadtripImg,
    stats: {
      difficulty: "Challenging / Experienced Riders",
      bestSeason: "April – June & September – November",
      duration: "4 – 10 Days",
      altitude: "Up to 11,500+ ft",
      idealFor: "Bikers, Roadtrippers, Riding Clubs",
    },
    highlights: [
      {
        icon: "ph-motorcycle-fill",
        title: "All-Terrain Himalayan Fleets",
        desc: "Ride fully serviced Royal Enfield Himalayan 450s & Scram 411s outfitted with crash guards and phone mounts.",
      },
      {
        icon: "ph-wrench-fill",
        title: "Dedicated Chase Truck & Mechanic",
        desc: "Complete backup vehicle carrying your heavy luggage, spare parts, tools, and a standby motorcycle.",
      },
      {
        icon: "ph-map-pin-line-fill",
        title: "High Mountain River Gorges",
        desc: "Conquer scenic highway routes along the Bhagirathi, Alaknanda, and Mandakini river valleys.",
      },
      {
        icon: "ph-camera-fill",
        title: "Curated Scenic Photo Stops",
        desc: "Pre-planned scenic pauses at cliffside roads, suspension bridges, and high-altitude alpine tea shacks.",
      },
    ],
    destinations: [
      {
        name: "Rishikesh to Badrinath & Mana",
        altitude: "10,500 ft",
        duration: "6 Days / 5 Nights",
        difficulty: "Challenging",
        tag: "Epic Highway Odyssey",
        desc: "Carve through the dramatic gorges of Panch Prayag to reach India's last frontier village at Mana.",
      },
      {
        name: "Mussoorie - Dhanaulti - Kanatal Ridge",
        altitude: "8,500 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Moderate",
        tag: "Panoramic Ridge Run",
        desc: "Smooth winding asphalt offering uninterrupted vistas of the Doon valley and the snow-capped Great Himalayas.",
      },
      {
        name: "Kumaon Circuit (Nainital - Almora - Kausani)",
        altitude: "7,000 ft",
        duration: "5 Days / 4 Nights",
        difficulty: "Moderate",
        tag: "Colonial & Tea Valley Ride",
        desc: "Glide through fragrant pine and deodar forests, lake districts, and tea plantations.",
      },
    ],
    included: [
      "Royal Enfield Himalayan 450 / Scram 411 Motorcycle with Fuel Allowance",
      "Support Vehicle (4x4 / Bolero Camper) for Luggage & Medical Equipment",
      "Professional Road Captain & Certified Lead Motorcycle Mechanic",
      "Handpicked Mountain Resort & Deluxe Camp Accommodation",
      "All Breakfasts, Trail Dinners & Welcome Refreshments",
    ],
    packingList: [
      "DOT / ECE certified full-face riding helmet",
      "All-weather motorcycle riding jacket and pants with CE Level 2 armor",
      "Waterproof riding boots with ankle and shin protection",
      "Winter and summer riding gloves (waterproof recommended)",
      "Rain gear / Over-suit for unexpected mountain showers",
      "Valid Two-Wheeler Driving License & Photo ID",
    ],
    faqs: [
      {
        q: "Can pillion riders join the motorcycle tour?",
        a: "Yes! Pillions are welcome on our Royal Enfield Himalayan bikes, or they can travel comfortably in the accompanying AC support backup vehicle.",
      },
      {
        q: "What if a motorcycle breaks down on a remote pass?",
        a: "Our chase vehicle carries full tools, spare components, and an extra motorcycle so your ride continues without delay.",
      },
    ],
    relatedTourIds: [9, 6, 8],
  },
  {
    id: 8,
    slug: "camping-and-stargazing",
    title: "Camping & Stargazing",
    badge: "Bortle-Class Dark Skies",
    tagline: "Camp under crystal-clear Himalayan skies, gaze at the Milky Way, and wake up to golden mountain sunrises.",
    description:
      "Spend nights under the clear Himalayan skies. Enjoy organized camping and breathtaking views.",
    overview:
      "Far removed from the haze and blinding light pollution of bustling cities, Uttarakhand is home to some of the world's most breathtaking dark sky sanctuaries. Locations like Chopta, Benital, Kanatal, and Deoriatal boast Bortle-Class 2 and 3 night skies where the Milky Way spans brilliantly from horizon to horizon with the naked eye. Cozy up around an alpine bonfire, look through high-powered telescopes to observe Saturn's rings, and sleep peacefully in comfortable all-weather dome tents.",
    icon: "ph-tent-fill",
    example: "Chopta, Kanatal, Deoriatal Campsites",
    color: "text-indigo-400",
    themeBg: "from-indigo-900 to-slate-950",
    accentBorder: "border-indigo-400",
    imageUrl: campingImg,
    stats: {
      difficulty: "Easy to Moderate",
      bestSeason: "October – May (Crisp dark skies & clear Milky Way)",
      duration: "2 – 5 Days",
      altitude: "6,500 – 10,000 ft",
      idealFor: "Stargazers, Couples, Campers, Astrophotographers",
    },
    highlights: [
      {
        icon: "ph-binoculars-fill",
        title: "Deep Sky Telescope Astronomy",
        desc: "Observe lunar craters, Jupiter's Galilean moons, Saturn's rings, and distant nebulae through high-aperture telescopes.",
      },
      {
        icon: "ph-camera-fill",
        title: "Milky Way Astrophotography",
        desc: "Guided evening workshops capturing the cosmic galaxy arching over the snow-crested Chaukhamba peaks.",
      },
      {
        icon: "ph-tent-fill",
        title: "Comfortable Alpine Glamping",
        desc: "Four-season waterproof dome tents equipped with insulated sleeping bags, plush foam mattresses, and warm fleece blankets.",
      },
      {
        icon: "ph-fire-fill",
        title: "Acoustic Bonfires & Hot Meals",
        desc: "Evenings around crackling campfires with steaming local Himalayan delicacies, hot chocolate, and acoustic tunes.",
      },
    ],
    destinations: [
      {
        name: "Chopta Alpine Meadows & Tungnath Base",
        altitude: "8,800 ft",
        duration: "3 Days / 2 Nights",
        difficulty: "Easy - Moderate",
        tag: "Mini Switzerland of India",
        desc: "Open grassy bugyals surrounded by deodars with unobstructed vistas of the massive Chaukhamba massif.",
      },
      {
        name: "Benital Dark Sky Astro Village",
        altitude: "8,500 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Easy",
        tag: "India's First Astro Village",
        desc: "State-recognized astronomy hub equipped with permanent telescope domes, stellar night views, and clean mountain air.",
      },
      {
        name: "Deoriatal High-Altitude Lake Camping",
        altitude: "7,800 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Moderate (3km Trek)",
        tag: "Mirrored Chaukhamba Reflection",
        desc: "Crystal mountain lake mirroring the snowy Himalayan peaks during the day and billions of stars at night.",
      },
      {
        name: "Kanatal & Dhanaulti Pine Forests",
        altitude: "7,500 ft",
        duration: "2 Days / 1 Night",
        difficulty: "Easy",
        tag: "Serene Weekend Escape",
        desc: "Dense pine and cedar clearings ideal for relaxation, hammocks, zip-lining, and tranquil stargazing.",
      },
    ],
    included: [
      "Deluxe All-Weather Alpine Dome Tents with Insulated Bedding",
      "Astronomical Telescope Sessions & Sky Guide Orientation",
      "Freshly Cooked Hot Camp Meals (Evening Snacks, Dinner, Breakfast)",
      "Evening Campfire with Music & Refreshments (subject to weather/forest norms)",
      "Clean Eco-Friendly Campsite Facilities & Common Washrooms",
    ],
    packingList: [
      "Thermal base layer, warm sweater, and down jacket (nights are very cold in high altitude)",
      "Woolen cap (beanie), warm socks, and gloves",
      "Red light headlamp or flashlight (red light preserves night vision for astronomy)",
      "Camera with manual exposure mode & sturdy tripod for astrophotography",
      "Thermos flask for hot water/tea through the night",
    ],
    faqs: [
      {
        q: "How cold does it get at night while camping?",
        a: "Temperatures in Chopta and high meadows can drop between 0°C to 8°C in winter and 8°C to 15°C in summer. High-grade thermal sleeping bags ensure cozy comfort.",
      },
      {
        q: "What is the best moon phase for stargazing?",
        a: "The week around the New Moon (Amavasya) is ideal, when the sky is darkest and the Milky Way core is vividly visible.",
      },
      {
        q: "Are the campsites safe for solo female travelers and families?",
        a: "Yes! All our campsites are secured with 24/7 staff, well-lit perimeter pathways, and family-friendly staff.",
      },
    ],
    relatedTourIds: [3, 5, 2],
  },
];

